// Just enough JSON Schema to drive forms from the session spec's own schema
// (`GET /api/flows/schema`, generated by schemars). Every field the spec
// gains appears in the Studio without a UI change.

import { isObject, type Json, type JsonObject } from './paths';

export interface Schema {
  $ref?: string;
  type?: string | string[];
  description?: string;
  title?: string;
  enum?: Json[];
  const?: Json;
  default?: Json;
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: boolean | Schema;
  items?: Schema | Schema[] | boolean;
  anyOf?: Schema[];
  oneOf?: Schema[];
  allOf?: Schema[];
  format?: string;
  minimum?: number;
  maximum?: number;
}

export interface RootSchema extends Schema {
  definitions?: Record<string, Schema>;
}

/** `true` in a schema position means "any JSON value". */
export type SchemaLike = Schema | boolean;

export type Kind =
  | 'string'
  | 'number'
  | 'integer'
  | 'boolean'
  | 'enum'
  | 'object'
  | 'map'
  | 'array'
  | 'tuple'
  | 'variants'
  | 'any';

/** Follow `$ref`s and single-element `allOf`s to the schema that matters. */
export function resolve(root: RootSchema, schema: SchemaLike | undefined): Schema {
  let current: SchemaLike | undefined = schema;
  for (let depth = 0; depth < 32; depth++) {
    if (current === undefined || current === true) return {};
    if (current === false) return { enum: [] };
    if (current.$ref) {
      const name = current.$ref.replace(/^#\/(definitions|\$defs)\//, '');
      const target = root.definitions?.[name];
      const { $ref: _ignored, ...rest } = current;
      current = target ? { ...target, ...pick(rest, ['description']) } : {};
      continue;
    }
    if (current.allOf && current.allOf.length === 1) {
      const { allOf, ...rest } = current;
      current = { ...resolve(root, allOf[0]), ...pick(rest, ['description', 'default']) };
      continue;
    }
    return current;
  }
  return {};
}

function pick(schema: Schema, keys: (keyof Schema)[]): Schema {
  const out: Schema = {};
  for (const key of keys) {
    if (schema[key] !== undefined) (out as Record<string, unknown>)[key] = schema[key];
  }
  return out;
}

function isNullSchema(schema: SchemaLike): boolean {
  return typeof schema === 'object' && (schema.type === 'null' || (schema.enum?.length === 1 && schema.enum[0] === null));
}

/** Split `anyOf: [X, null]` and `type: [T, "null"]` into X and "may be null". */
export function unwrapNullable(root: RootSchema, schema: SchemaLike | undefined): { schema: Schema; nullable: boolean } {
  const resolved = resolve(root, schema);
  const alternatives = resolved.anyOf ?? resolved.oneOf;
  if (alternatives && alternatives.some(isNullSchema)) {
    const rest = alternatives.filter((s) => !isNullSchema(s));
    const inner: Schema = rest.length === 1 ? resolve(root, rest[0]) : { ...resolved, anyOf: rest, oneOf: undefined };
    return { schema: { ...inner, description: resolved.description ?? inner.description }, nullable: true };
  }
  if (Array.isArray(resolved.type) && resolved.type.includes('null')) {
    const types = resolved.type.filter((t) => t !== 'null');
    return { schema: { ...resolved, type: types.length === 1 ? types[0] : types }, nullable: true };
  }
  return { schema: resolved, nullable: false };
}

export function kindOf(root: RootSchema, schema: SchemaLike | undefined): Kind {
  const s = resolve(root, schema);
  if (s.oneOf || s.anyOf) return 'variants';
  if (s.enum) return 'enum';
  const type = Array.isArray(s.type) ? s.type.find((t) => t !== 'null') : s.type;
  switch (type) {
    case 'string':
      return 'string';
    case 'integer':
      return 'integer';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return Array.isArray(s.items) ? 'tuple' : 'array';
    case 'object':
      if (s.properties) return 'object';
      if (s.additionalProperties !== undefined && s.additionalProperties !== false) return 'map';
      return 'object';
    default:
      if (s.properties) return 'object';
      return 'any';
  }
}

export interface Variant {
  /** Short name: the enum value or the object's single key. */
  label: string;
  description?: string;
  schema: Schema;
  matches(value: Json | undefined): boolean;
  make(): Json;
}

/** The alternatives of a `oneOf`/`anyOf`, each able to recognize its own
 * values and to make a fresh one (externally tagged enums serialize as a
 * string or as an object with a single key). */
export function variants(root: RootSchema, schema: SchemaLike | undefined): Variant[] {
  const s = resolve(root, schema);
  const alternatives = (s.oneOf ?? s.anyOf ?? []).map((a) => resolve(root, a));
  const out: Variant[] = [];
  for (const alt of alternatives) {
    if (alt.enum) {
      for (const value of alt.enum) {
        out.push({
          label: String(value),
          description: alt.description,
          schema: alt,
          matches: (v) => v === value,
          make: () => value,
        });
      }
      continue;
    }
    const keys = Object.keys(alt.properties ?? {});
    if (kindOf(root, alt) === 'object' && alt.required?.length === 1 && keys.length === 1) {
      const key = keys[0]!;
      out.push({
        label: key,
        description: alt.description,
        schema: alt,
        matches: (v) => isObject(v) && Object.keys(v).length === 1 && key in v,
        make: () => ({ [key]: defaultFor(root, alt.properties![key]) }),
      });
      continue;
    }
    const kind = kindOf(root, alt);
    out.push({
      label: alt.title ?? (kind === 'object' ? 'object' : kind),
      description: alt.description,
      schema: alt,
      matches: (v) => matchesKind(kind, v, alt),
      make: () => defaultFor(root, alt),
    });
  }
  return out;
}

function matchesKind(kind: Kind, value: Json | undefined, schema: Schema): boolean {
  switch (kind) {
    case 'string':
      return typeof value === 'string';
    case 'integer':
    case 'number':
      return typeof value === 'number';
    case 'boolean':
      return typeof value === 'boolean';
    case 'array':
    case 'tuple':
      return Array.isArray(value);
    case 'object':
    case 'map':
      if (!isObject(value)) return false;
      return (schema.required ?? []).every((k) => k in value);
    default:
      return value !== undefined;
  }
}

/** The variant a value belongs to, if any. */
export function variantOf(root: RootSchema, schema: SchemaLike | undefined, value: Json | undefined): number {
  return variants(root, schema).findIndex((v) => v.matches(value));
}

/** A minimal valid value: required fields only. */
export function defaultFor(root: RootSchema, schema: SchemaLike | undefined): Json {
  const { schema: s, nullable } = unwrapNullable(root, schema);
  if (s.default !== undefined) return s.default;
  if (nullable) return null;
  switch (kindOf(root, s)) {
    case 'string':
      return '';
    case 'integer':
    case 'number':
      return 0;
    case 'boolean':
      return false;
    case 'enum':
      return s.enum?.[0] ?? null;
    case 'array':
      return [];
    case 'tuple':
      return (s.items as SchemaLike[]).map((item) => defaultFor(root, item));
    case 'map':
      return {};
    case 'object': {
      const out: JsonObject = {};
      for (const key of s.required ?? []) out[key] = defaultFor(root, s.properties?.[key]);
      return out;
    }
    case 'variants':
      return variants(root, s)[0]?.make() ?? null;
    default:
      return null;
  }
}

/** Description text without rustdoc link syntax. */
export function describe(text: string | undefined): string {
  if (!text) return '';
  return text
    .replace(/\[`?([^\]`]+)`?\]\([^)]*\)/g, '$1')
    .replace(/\[`([^\]`]+)`\]/g, '$1')
    .trim();
}

/** A field name as a label: `save_response_as` → "Save response as". */
export function labelFor(key: string): string {
  const words = key.replace(/_/g, ' ').trim();
  return words.charAt(0).toUpperCase() + words.slice(1);
}
