//! Code generation for js-genai types into per-module Rust files.
//!
//! Generates rs-genai type stubs organized by GenaiTypeCategory,
//! producing one file per category/module.

use std::collections::HashMap;
use std::path::Path;

use crate::schema::{GenaiSchema, GenaiTypeCategory, GenaiTypeDef};

/// Result of module-aware genai code generation.
/// Maps module name → generated Rust source code.
pub struct GenaiModuleOutput {
    /// Map of module name (e.g. "generate", "embed") → Rust source code
    pub modules: HashMap<String, String>,
    /// The mod.rs re-export file
    pub mod_rs: String,
}

/// Generate per-module Rust source files from a GenaiSchema.
///
/// Types that already have wire equivalents are skipped (they exist in rs-genai).
/// Types without wire equivalents get stub struct/enum definitions generated.
pub fn generate_genai_modules(schema: &GenaiSchema) -> GenaiModuleOutput {
    // Group types by category
    let mut by_category: HashMap<GenaiTypeCategory, Vec<&GenaiTypeDef>> = HashMap::new();

    for t in &schema.types {
        if !t.has_wire_equivalent {
            by_category.entry(t.category.clone()).or_default().push(t);
        }
    }

    let mut modules = HashMap::new();

    for (category, types) in &by_category {
        let module_name = category.module_name();
        let code = generate_module_file(module_name, types, &schema.source.framework);
        modules.insert(module_name.to_string(), code);
    }

    // Generate mod.rs
    let mut mod_rs = String::new();
    mod_rs.push_str("// AUTO-GENERATED by adk-transpiler -- do not edit manually\n\n");

    let mut module_names: Vec<&String> = modules.keys().collect();
    module_names.sort();

    for name in &module_names {
        mod_rs.push_str(&format!("pub mod {};\n", name));
    }
    mod_rs.push('\n');

    // Re-export all types
    for name in &module_names {
        mod_rs.push_str(&format!("pub use {}::*;\n", name));
    }

    GenaiModuleOutput { modules, mod_rs }
}

/// Write the generated modules to an output directory.
pub fn write_genai_modules(output: &GenaiModuleOutput, output_dir: &Path) -> Result<(), String> {
    std::fs::create_dir_all(output_dir)
        .map_err(|e| format!("Failed to create output dir: {}", e))?;

    // Write mod.rs
    std::fs::write(output_dir.join("mod.rs"), &output.mod_rs)
        .map_err(|e| format!("Failed to write mod.rs: {}", e))?;

    // Write per-module files
    for (name, code) in &output.modules {
        let path = output_dir.join(format!("{}.rs", name));
        std::fs::write(&path, code)
            .map_err(|e| format!("Failed to write {}: {}", path.display(), e))?;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Per-module file generation
// ---------------------------------------------------------------------------

fn generate_module_file(module_name: &str, types: &[&GenaiTypeDef], framework: &str) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "// AUTO-GENERATED by adk-transpiler from {} -- do not edit manually\n",
        framework
    ));
    out.push_str(&format!("// Module: {}\n\n", module_name));
    out.push_str("#![allow(dead_code)]\n\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");

    for t in types {
        out.push_str(&generate_type_stub(t));
        out.push('\n');
    }

    out
}

fn generate_type_stub(t: &GenaiTypeDef) -> String {
    let mut out = String::new();

    // Doc comment
    if let Some(desc) = &t.description {
        for line in desc.lines() {
            out.push_str(&format!("/// {}\n", line));
        }
    }

    if t.fields.is_empty() {
        // Empty struct (marker type)
        out.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{}}\n", t.name));
    } else {
        // Check if all fields are optional (can derive Default)
        let all_optional = t.fields.iter().all(|f| f.optional);
        if all_optional {
            out.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n");
        } else {
            out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        }
        out.push_str(&format!("pub struct {} {{\n", t.name));

        for field in &t.fields {
            if let Some(desc) = &field.description {
                out.push_str(&format!("    /// {}\n", desc));
            }

            let rust_name = to_snake_case(&field.name);
            let rust_type = map_genai_field_type(&field.rust_type, field.optional);

            // Add serde rename if snake_case differs from original
            if rust_name != field.name {
                out.push_str(&format!("    #[serde(rename = \"{}\")]\n", field.name));
            }
            if field.optional {
                out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
            }
            out.push_str(&format!("    pub {}: {},\n", rust_name, rust_type));
        }

        out.push_str("}\n");
    }

    out
}

/// Map a genai field type to a Rust type for stub generation.
fn map_genai_field_type(rust_type: &str, optional: bool) -> String {
    let base = match rust_type {
        "serde_json::Value" => "serde_json::Value".to_string(),
        t if t.starts_with("Vec<") => t.to_string(),
        t if t.starts_with("rs_genai::") => t.to_string(),
        "String" => "String".to_string(),
        "bool" => "bool".to_string(),
        "f64" => "f64".to_string(),
        "()" => "()".to_string(),
        t => {
            // Unknown types become serde_json::Value in stubs
            if t.starts_with("/*") || t.contains("Ref") {
                "serde_json::Value".to_string()
            } else {
                t.to_string()
            }
        }
    };

    if optional {
        format!("Option<{}>", base)
    } else {
        base
    }
}

/// Convert camelCase to snake_case.
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::{FieldDef, SourceInfo};

    fn make_genai_schema(types: Vec<GenaiTypeDef>) -> GenaiSchema {
        GenaiSchema {
            source: SourceInfo {
                framework: "js-genai".to_string(),
                source_dir: "/tmp/test".to_string(),
                extracted_at: "2026-01-01T00:00:00Z".to_string(),
            },
            types,
            enums: vec![],
            type_aliases: vec![],
            helpers: vec![],
            rest_modules: vec![],
        }
    }

    #[test]
    fn generates_per_module_output() {
        let types = vec![
            GenaiTypeDef {
                name: "GenerateContentResponse".to_string(),
                category: GenaiTypeCategory::Generate,
                description: Some("Response from generateContent".to_string()),
                fields: vec![FieldDef {
                    name: "candidates".to_string(),
                    ts_type: "Candidate[]".to_string(),
                    rust_type: "Vec<Candidate>".to_string(),
                    optional: true,
                    default_value: None,
                    description: None,
                }],
                extends: None,
                wire_type: None,
                has_wire_equivalent: false,
            },
            GenaiTypeDef {
                name: "EmbedContentRequest".to_string(),
                category: GenaiTypeCategory::Embed,
                description: None,
                fields: vec![],
                extends: None,
                wire_type: None,
                has_wire_equivalent: false,
            },
        ];

        let output = generate_genai_modules(&make_genai_schema(types));

        assert!(output.modules.contains_key("generate"));
        assert!(output.modules.contains_key("embed"));
        assert!(output
            .modules
            .get("generate")
            .unwrap()
            .contains("GenerateContentResponse"));
        assert!(output
            .modules
            .get("embed")
            .unwrap()
            .contains("EmbedContentRequest"));
        assert!(output.mod_rs.contains("pub mod generate;"));
        assert!(output.mod_rs.contains("pub mod embed;"));
    }

    #[test]
    fn skips_types_with_wire_equivalent() {
        let types = vec![GenaiTypeDef {
            name: "Content".to_string(),
            category: GenaiTypeCategory::Content,
            description: None,
            fields: vec![],
            extends: None,
            wire_type: Some("rs_genai::prelude::Content".to_string()),
            has_wire_equivalent: true,
        }];

        let output = generate_genai_modules(&make_genai_schema(types));
        assert!(
            output.modules.is_empty(),
            "Should skip types with wire equivalents"
        );
    }

    #[test]
    fn to_snake_case_works() {
        assert_eq!(to_snake_case("fooBar"), "foo_bar");
        assert_eq!(
            to_snake_case("generateContentConfig"),
            "generate_content_config"
        );
        assert_eq!(to_snake_case("name"), "name");
    }
}
