//! Code generation for REST API modules.
//!
//! Generates complete Rust REST modules from `RestModuleDef` definitions:
//! error enum, `impl Client` block with async methods, and unit tests.

use std::collections::HashMap;
use std::path::Path;

use crate::schema::genai::{HttpMethod, RestMethodDef, RestModuleDef};

/// Result of REST module code generation.
pub struct RestModuleOutput {
    /// Map of module name → generated Rust source code
    pub modules: HashMap<String, String>,
}

/// Generate Rust REST modules from extracted definitions.
pub fn generate_rest_modules(modules: &[RestModuleDef]) -> RestModuleOutput {
    let mut output = HashMap::new();

    for module in modules {
        let code = generate_rest_module(module);
        output.insert(module.name.clone(), code);
    }

    RestModuleOutput { modules: output }
}

/// Generate a complete Rust REST module from a `RestModuleDef`.
pub fn generate_rest_module(module: &RestModuleDef) -> String {
    let mut out = String::new();

    // Header
    out.push_str("// AUTO-GENERATED by adk-transpiler -- do not edit manually\n");
    out.push_str(&format!(
        "//! {} API — feature-gated behind `{}`.\n\n",
        module.class_name, module.name
    ));

    // Imports
    out.push_str("use serde::{Deserialize, Serialize};\n\n");
    out.push_str("use crate::client::http::HttpError;\n");
    out.push_str("use crate::client::Client;\n");
    out.push_str("use crate::transport::auth::ServiceEndpoint;\n\n");

    // Error enum
    out.push_str(&generate_error_enum(&module.error_type));
    out.push('\n');

    // impl Client block
    out.push_str(&generate_client_impl(module));
    out.push('\n');

    // Tests
    out.push_str(&generate_tests(module));

    out
}

/// Write generated REST modules to an output directory.
pub fn write_rest_modules(output: &RestModuleOutput, output_dir: &Path) -> Result<(), String> {
    for (name, code) in &output.modules {
        let module_dir = output_dir.join(name);
        std::fs::create_dir_all(&module_dir)
            .map_err(|e| format!("Failed to create dir {}: {e}", module_dir.display()))?;

        let path = module_dir.join("mod.rs");
        std::fs::write(&path, code)
            .map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
    }

    Ok(())
}

// ── Error Enum ──────────────────────────────────────────────────────────────

fn generate_error_enum(error_type: &str) -> String {
    format!(
        r#"/// Errors from this API module.
#[derive(Debug, thiserror::Error)]
pub enum {error_type} {{
    #[error(transparent)]
    Http(#[from] HttpError),
    #[error("Failed to parse response: {{0}}")]
    Parse(#[from] serde_json::Error),
    #[error("Auth error: {{0}}")]
    Auth(String),
}}
"#
    )
}

// ── Client Impl ─────────────────────────────────────────────────────────────

fn generate_client_impl(module: &RestModuleDef) -> String {
    let mut out = String::new();
    out.push_str("impl Client {\n");

    for method in &module.methods {
        if method.is_special {
            out.push_str(&generate_special_stub(method, module));
        } else {
            out.push_str(&generate_client_method(method, module));
        }
        out.push('\n');
    }

    out.push_str("}\n");
    out
}

fn generate_client_method(method: &RestMethodDef, module: &RestModuleDef) -> String {
    let error_type = &module.error_type;
    let endpoint = &module.service_endpoint;

    // Add doc comment
    let mut out = String::new();
    if let Some(desc) = &method.description {
        out.push_str(&format!("    /// {desc}\n"));
    }

    match method.http_method {
        HttpMethod::Get if method.ts_name == "list" => {
            // List pattern: GET base URL, return ListXxxResponse
            let return_type = &method.return_type;
            let list_field = infer_list_field(&module.name);
            out.push_str(&format!(
                r#"    pub async fn {name}(&self) -> Result<{return_type}, {error_type}> {{
        let url = self.rest_url(ServiceEndpoint::{endpoint});
        let headers = self
            .auth_headers()
            .await
            .map_err(|e| {error_type}::Auth(e.to_string()))?;
        let json = self.http_client().get_json(&url, headers).await?;
        if json.is_null() {{
            return Ok({return_type} {{
                {list_field}: vec![],
                next_page_token: None,
            }});
        }}
        Ok(serde_json::from_value(json)?)
    }}
"#,
                name = method.rust_name,
            ));
        }
        HttpMethod::Get => {
            // Get-by-name pattern
            let return_type = &method.return_type;
            out.push_str(&format!(
                r#"    pub async fn {name}(&self, name: &str) -> Result<{return_type}, {error_type}> {{
        let base_url = self.rest_url(ServiceEndpoint::{endpoint});
        let url = format!("{{base_url}}/{{name}}");
        let headers = self
            .auth_headers()
            .await
            .map_err(|e| {error_type}::Auth(e.to_string()))?;
        let json = self.http_client().get_json(&url, headers).await?;
        Ok(serde_json::from_value(json)?)
    }}
"#,
                name = method.rust_name,
            ));
        }
        HttpMethod::Post if method.returns_void => {
            // Cancel pattern: POST to name:cancel with empty body
            out.push_str(&format!(
                r#"    pub async fn {name}(&self, name: &str) -> Result<(), {error_type}> {{
        let base_url = self.rest_url(ServiceEndpoint::{endpoint});
        let url = format!("{{base_url}}/{{name}}:cancel");
        let headers = self
            .auth_headers()
            .await
            .map_err(|e| {error_type}::Auth(e.to_string()))?;
        self.http_client()
            .post_json(&url, headers, &serde_json::json!({{}}))
            .await?;
        Ok(())
    }}
"#,
                name = method.rust_name,
            ));
        }
        HttpMethod::Post => {
            // Create pattern: POST with body
            let return_type = &method.return_type;
            out.push_str(&format!(
                r#"    pub async fn {name}(
        &self,
        body: &impl serde::Serialize,
    ) -> Result<{return_type}, {error_type}> {{
        let url = self.rest_url(ServiceEndpoint::{endpoint});
        let headers = self
            .auth_headers()
            .await
            .map_err(|e| {error_type}::Auth(e.to_string()))?;
        let json = self.http_client().post_json(&url, headers, body).await?;
        Ok(serde_json::from_value(json)?)
    }}
"#,
                name = method.rust_name,
            ));
        }
        HttpMethod::Patch => {
            // Update pattern: PATCH with body
            let return_type = &method.return_type;
            out.push_str(&format!(
                r#"    pub async fn {name}(
        &self,
        name: &str,
        body: &impl serde::Serialize,
    ) -> Result<{return_type}, {error_type}> {{
        let base_url = self.rest_url(ServiceEndpoint::{endpoint});
        let url = format!("{{base_url}}/{{name}}");
        let headers = self
            .auth_headers()
            .await
            .map_err(|e| {error_type}::Auth(e.to_string()))?;
        let json = self.http_client().patch_json(&url, headers, body).await?;
        Ok(serde_json::from_value(json)?)
    }}
"#,
                name = method.rust_name,
            ));
        }
        HttpMethod::Delete => {
            // Delete pattern
            out.push_str(&format!(
                r#"    pub async fn {name}(&self, name: &str) -> Result<(), {error_type}> {{
        let base_url = self.rest_url(ServiceEndpoint::{endpoint});
        let url = format!("{{base_url}}/{{name}}");
        let headers = self
            .auth_headers()
            .await
            .map_err(|e| {error_type}::Auth(e.to_string()))?;
        self.http_client().delete(&url, headers).await?;
        Ok(())
    }}
"#,
                name = method.rust_name,
            ));
        }
        HttpMethod::Put => {
            // Put pattern (similar to POST)
            let return_type = &method.return_type;
            out.push_str(&format!(
                r#"    pub async fn {name}(
        &self,
        body: &impl serde::Serialize,
    ) -> Result<{return_type}, {error_type}> {{
        let url = self.rest_url(ServiceEndpoint::{endpoint});
        let headers = self
            .auth_headers()
            .await
            .map_err(|e| {error_type}::Auth(e.to_string()))?;
        let json = self.http_client().put_json(&url, headers, body).await?;
        Ok(serde_json::from_value(json)?)
    }}
"#,
                name = method.rust_name,
            ));
        }
    }

    out
}

fn generate_special_stub(method: &RestMethodDef, module: &RestModuleDef) -> String {
    let mut out = String::new();
    if let Some(desc) = &method.description {
        out.push_str(&format!("    /// {desc}\n"));
    }
    out.push_str(&format!(
        "    // TODO: {} requires manual implementation (special upload/download logic)\n",
        method.rust_name
    ));
    out.push_str(&format!(
        "    // pub async fn {}(&self, ...) -> Result<..., {}> {{ ... }}\n",
        method.rust_name, module.error_type
    ));
    out
}

/// Infer the list response field name from the module name.
fn infer_list_field(module_name: &str) -> &str {
    match module_name {
        "files" => "files",
        "caches" => "cached_contents",
        "tunings" => "tuning_jobs",
        "batches" => "batch_jobs",
        "models" => "models",
        _ => "items",
    }
}

// ── Tests ───────────────────────────────────────────────────────────────────

fn generate_tests(module: &RestModuleDef) -> String {
    let mut out = String::new();
    out.push_str("#[cfg(test)]\nmod tests {\n    use super::*;\n\n");

    out.push_str(&format!(
        "    #[test]\n    fn {}_error_variants() {{\n",
        module.name
    ));
    out.push_str(&format!(
        "        let _http = {}::Auth(\"test\".to_string());\n",
        module.error_type
    ));
    out.push_str("    }\n");

    out.push_str("}\n");
    out
}

// ── Unit Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_module() -> RestModuleDef {
        RestModuleDef {
            name: "files".to_string(),
            class_name: "Files".to_string(),
            service_endpoint: "Files".to_string(),
            error_type: "FilesError".to_string(),
            methods: vec![
                RestMethodDef {
                    ts_name: "list".to_string(),
                    rust_name: "list_files".to_string(),
                    http_method: HttpMethod::Get,
                    return_type: "ListFilesResponse".to_string(),
                    description: Some("List files.".to_string()),
                    is_special: false,
                    returns_void: false,
                },
                RestMethodDef {
                    ts_name: "get".to_string(),
                    rust_name: "get_file".to_string(),
                    http_method: HttpMethod::Get,
                    return_type: "File".to_string(),
                    description: Some("Get a file by name.".to_string()),
                    is_special: false,
                    returns_void: false,
                },
                RestMethodDef {
                    ts_name: "delete".to_string(),
                    rust_name: "delete_file".to_string(),
                    http_method: HttpMethod::Delete,
                    return_type: String::new(),
                    description: None,
                    is_special: false,
                    returns_void: true,
                },
                RestMethodDef {
                    ts_name: "upload".to_string(),
                    rust_name: "upload_file".to_string(),
                    http_method: HttpMethod::Post,
                    return_type: "File".to_string(),
                    description: None,
                    is_special: true,
                    returns_void: false,
                },
            ],
        }
    }

    #[test]
    fn generates_error_enum() {
        let code = generate_error_enum("FilesError");
        assert!(code.contains("pub enum FilesError"));
        assert!(code.contains("Http(#[from] HttpError)"));
        assert!(code.contains("Parse(#[from] serde_json::Error)"));
        assert!(code.contains("Auth(String)"));
    }

    #[test]
    fn generates_list_method() {
        let module = sample_module();
        let code = generate_rest_module(&module);
        assert!(code.contains("pub async fn list_files(&self)"));
        assert!(code.contains("-> Result<ListFilesResponse, FilesError>"));
        assert!(code.contains("ServiceEndpoint::Files"));
        assert!(code.contains("get_json"));
    }

    #[test]
    fn generates_get_method() {
        let module = sample_module();
        let code = generate_rest_module(&module);
        assert!(code.contains("pub async fn get_file(&self, name: &str)"));
        assert!(code.contains("-> Result<File, FilesError>"));
        assert!(code.contains("format!(\"{base_url}/{name}\")"));
    }

    #[test]
    fn generates_delete_method() {
        let module = sample_module();
        let code = generate_rest_module(&module);
        assert!(code.contains("pub async fn delete_file(&self, name: &str)"));
        assert!(code.contains("-> Result<(), FilesError>"));
        assert!(code.contains("delete(&url"));
    }

    #[test]
    fn generates_special_stub() {
        let module = sample_module();
        let code = generate_rest_module(&module);
        assert!(code.contains("TODO: upload_file requires manual implementation"));
    }

    #[test]
    fn generates_full_module() {
        let module = sample_module();
        let code = generate_rest_module(&module);
        // Should have all sections
        assert!(code.contains("AUTO-GENERATED"));
        assert!(code.contains("use serde::{Deserialize, Serialize}"));
        assert!(code.contains("pub enum FilesError"));
        assert!(code.contains("impl Client {"));
        assert!(code.contains("#[cfg(test)]"));
    }

    #[test]
    fn generates_cancel_method() {
        let module = RestModuleDef {
            name: "batches".to_string(),
            class_name: "Batches".to_string(),
            service_endpoint: "BatchJobs".to_string(),
            error_type: "BatchesError".to_string(),
            methods: vec![RestMethodDef {
                ts_name: "cancel".to_string(),
                rust_name: "cancel_batch_job".to_string(),
                http_method: HttpMethod::Post,
                return_type: String::new(),
                description: None,
                is_special: false,
                returns_void: true,
            }],
        };
        let code = generate_rest_module(&module);
        assert!(code.contains("pub async fn cancel_batch_job(&self, name: &str)"));
        assert!(code.contains("-> Result<(), BatchesError>"));
        assert!(code.contains(":cancel"));
    }

    #[test]
    fn generates_patch_method() {
        let module = RestModuleDef {
            name: "caches".to_string(),
            class_name: "Caches".to_string(),
            service_endpoint: "CachedContents".to_string(),
            error_type: "CachesError".to_string(),
            methods: vec![RestMethodDef {
                ts_name: "update".to_string(),
                rust_name: "update_cached_content".to_string(),
                http_method: HttpMethod::Patch,
                return_type: "CachedContent".to_string(),
                description: None,
                is_special: false,
                returns_void: false,
            }],
        };
        let code = generate_rest_module(&module);
        assert!(code.contains("pub async fn update_cached_content"));
        assert!(code.contains("patch_json"));
        assert!(code.contains("-> Result<CachedContent, CachesError>"));
    }
}
