//! Typed graph macros — compile-time-checked names for flow authoring.
//!
//! Flow/stage/tool/slot names are stringly by nature, which makes typos a runtime
//! surprise. [`voice_flow!`](crate::voice_flow) generates a module of `&'static str`
//! name constants so the names are declared once and every reference is checked at
//! compile time — a typo'd `booking::collct` is a build error, not a silent
//! never-matching guard.
//!
//! ```
//! use gemini_adk_fluent_rs::voice_flow;
//!
//! voice_flow! {
//!     mod booking {
//!         steps: [collect, confirm, done];
//!         tools: [book];
//!         slots: [party_size];
//!     }
//! }
//!
//! assert_eq!(booking::collect, "collect");
//! assert_eq!(booking::book, "book");
//! assert_eq!(booking::party_size, "party_size");
//! ```
//!
//! Use the constants throughout the [`Conversation`](crate::conversation::Conversation)
//! builder (`.stage(booking::collect)`, `.commit(booking::book, ..)`,
//! `Guard::captured([booking::party_size])`) so renaming a name is one edit and
//! mistyping it never compiles. (A full declarative `voice_flow!` body — stages,
//! transitions, and guards in macro syntax — is a planned follow-up; this is the
//! name-checking core.)

/// Generate a module of compile-time-checked flow name constants.
///
/// See the [module docs](crate::flow_macros) for usage.
#[macro_export]
macro_rules! voice_flow {
    (
        mod $module:ident {
            $( steps: [ $($step:ident),* $(,)? ]; )?
            $( tools: [ $($tool:ident),* $(,)? ]; )?
            $( slots: [ $($slot:ident),* $(,)? ]; )?
        }
    ) => {
        /// Compile-time-checked flow names generated by `voice_flow!`.
        #[allow(non_upper_case_globals)]
        #[allow(
            unreachable_pub,
            reason = "exported macro: the module is public API in the caller's crate, and \
                      whether it is reachable from that crate's root depends on where the \
                      caller expands it"
        )]
        pub mod $module {
            $( $(
                #[doc = concat!("Step id `", stringify!($step), "`.")]
                pub const $step: &str = stringify!($step);
            )* )?
            $( $(
                #[doc = concat!("Tool name `", stringify!($tool), "`.")]
                pub const $tool: &str = stringify!($tool);
            )* )?
            $( $(
                #[doc = concat!("Slot/state key `", stringify!($slot), "`.")]
                pub const $slot: &str = stringify!($slot);
            )* )?
        }
    };
}

#[cfg(test)]
mod tests {
    use crate::conversation::Conversation;
    use gemini_adk_rs::flow::Guard;

    voice_flow! {
        mod booking {
            steps: [collect, confirm, done];
            tools: [book];
            slots: [party_size];
        }
    }

    #[test]
    fn generated_constants_have_string_values() {
        assert_eq!(booking::collect, "collect");
        assert_eq!(booking::confirm, "confirm");
        assert_eq!(booking::book, "book");
        assert_eq!(booking::party_size, "party_size");
    }

    #[test]
    fn names_drive_a_real_conversation() {
        // Every name is the typed constant — a typo would not compile.
        let convo = Conversation::new("booking")
            .stage(booking::collect)
            .collect([booking::party_size])
            .next(booking::confirm, Guard::captured([booking::party_size]))
            .stage(booking::confirm)
            .commit(booking::book, Guard::is_true("user_confirmed"))
            .next(booking::done, Guard::called_ok(booking::book))
            .stage(booking::done)
            .terminal()
            .require([booking::done])
            .compile()
            .expect("compiles");
        assert!(convo.flow().tool_surface().tools.contains(booking::book));
    }

    // Sections are optional and order-independent.
    voice_flow! {
        mod tools_only {
            tools: [transfer];
        }
    }

    #[test]
    fn optional_sections() {
        assert_eq!(tools_only::transfer, "transfer");
    }
}
