//! Generate a standalone Rust application from a [`SessionSpec`].
//!
//! Because L2 never invents runtime semantics — every spec field lowers to a
//! builder method — code generation is *pretty-printing*, not compilation:
//! [`SessionSpec::to_rust`] emits the fluent `Live::builder()` chain the
//! document is equivalent to, as a complete `main.rs` (with a matching
//! `Cargo.toml` from [`SessionSpec::to_cargo_toml`]). The Studio's **Code**
//! tab serves both: draw the flow, read the program; edit the JSON, the
//! program follows.

use std::fmt::Write as _;

use gemini_adk_rs::flow::{Constraint, Flow, Guard, Pred};
use serde_json::Value;

use super::{
    EffectSpec, PromotePolicy, SessionSpec, SpecModality, ToolSpec, TriggerSpec, WatchCondition,
};

impl SessionSpec {
    /// The complete `main.rs` this spec is equivalent to.
    pub fn to_rust(&self) -> String {
        let mut out = String::new();
        let name = if self.name.is_empty() {
            "app"
        } else {
            &self.name
        };
        let _ = writeln!(
            out,
            "//! {name} — generated by Flow Studio from a SessionSpec."
        );
        if !self.description.is_empty() {
            let _ = writeln!(out, "//! {}", self.description);
        }
        out.push_str("//!\n//! The chain below is exactly what the JSON document lowers to;\n");
        out.push_str("//! edit either — they stay equivalent.\n\n");
        out.push_str("use serde_json::json;\n");
        out.push_str("use gemini_adk_fluent_rs::prelude::*;\n");
        if !self.extract.is_empty() {
            out.push_str(
                "use gemini_adk_fluent_rs::gemini_adk_rs::live::extractor::{\n    \
                 ExtractionTrigger, FieldPromotion, LlmExtractor,\n};\n",
            );
            out.push_str("use std::sync::Arc;\n");
        }
        out.push('\n');
        out.push_str(
            "#[tokio::main]\nasync fn main() -> Result<(), Box<dyn std::error::Error>> {\n",
        );
        out.push_str("    let state = State::new();\n\n");

        if !self.tools.is_empty() {
            out.push_str("    // ── Tools ──────────────────────────────────────────────\n");
            out.push_str("    let mut tools = ToolDispatcher::new();\n");
            for tool in &self.tools {
                out.push_str(&gen_tool(tool));
            }
            out.push('\n');
        }

        let flow = self.effective_flow().unwrap_or_default();
        if !flow.steps.is_empty() {
            out.push_str("    // ── Governed flow ──────────────────────────────────────\n");
            out.push_str(&gen_flow(&flow));
            out.push('\n');
        }

        out.push_str("    // ── Session ────────────────────────────────────────────\n");
        out.push_str("    let session = Live::builder()\n");
        let instruction = if self.instruction.is_empty() {
            "Follow the conversation flow you are given."
        } else {
            &self.instruction
        };
        let _ = writeln!(out, "        .instruction({})", rust_str(instruction));
        if let Some(greeting) = &self.greeting {
            let _ = writeln!(out, "        .greeting({})", rust_str(greeting));
        }
        match self.modality {
            SpecModality::Text => out.push_str("        .text_only()\n"),
            SpecModality::Audio => {
                let voice = self.voice.as_deref().unwrap_or("Puck");
                let known = ["Puck", "Aoede", "Charon", "Fenrir", "Kore"];
                if known.contains(&voice) {
                    let _ = writeln!(out, "        .voice(Voice::{voice})");
                } else {
                    let _ = writeln!(
                        out,
                        "        .voice(Voice::Custom({}.into()))",
                        rust_str(voice)
                    );
                }
            }
        }
        out.push_str("        .with_state(state.clone())\n");
        if !self.tools.is_empty() {
            out.push_str("        .tools(tools)\n");
        }
        for params in &self.mcp {
            let _ = writeln!(out, "        .with_tools(T::mcp({}))", rust_str(params));
        }
        if !flow.steps.is_empty() {
            out.push_str("        .govern(flow)\n");
        }
        for extract in &self.extract {
            out.push_str(&gen_extract(extract));
        }
        for phase in &self.phases {
            out.push_str(&gen_phase(phase));
        }
        if let Some(initial) = &self.initial_phase {
            let _ = writeln!(out, "        .initial_phase({})", rust_str(initial));
        }
        for watch in &self.watch {
            out.push_str(&gen_watch(watch));
        }
        if self.modality == SpecModality::Text {
            out.push_str("        .on_text(|t| print!(\"{t}\"))\n");
            out.push_str("        .on_turn_complete(|| async { println!(); })\n");
        }
        out.push_str("        .connect_from_env()\n        .await?;\n\n");

        match self.modality {
            SpecModality::Audio => {
                out.push_str(
                    "    // Microphone in, speakers out, barge-in handled.\n    \
                     // Requires the `voice-io` feature (see Cargo.toml).\n    \
                     session.talk().await?;\n",
                );
            }
            SpecModality::Text => {
                out.push_str(
                    "    // Minimal text REPL — type a line, read the reply.\n    \
                     let stdin = std::io::stdin();\n    \
                     let mut line = String::new();\n    \
                     while stdin.read_line(&mut line)? > 0 {\n        \
                     session.send_text(line.trim()).await?;\n        \
                     line.clear();\n    }\n    \
                     session.disconnect().await?;\n",
                );
            }
        }
        out.push_str("    Ok(())\n}\n");
        out
    }

    /// A `Cargo.toml` to pair with [`to_rust`](Self::to_rust).
    pub fn to_cargo_toml(&self) -> String {
        let name = if self.name.is_empty() {
            "flow-app".to_string()
        } else {
            self.name.replace([' ', '_'], "-").to_lowercase()
        };
        let features = if self.modality == SpecModality::Audio {
            r#", features = ["gemini-llm", "voice-io"]"#
        } else {
            r#", features = ["gemini-llm"]"#
        };
        format!(
            "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n\
             [dependencies]\ngemini-adk-fluent-rs = {{ version = \"0.8\"{features} }}\n\
             tokio = {{ version = \"1\", features = [\"full\"] }}\n\
             serde_json = \"1\"\n"
        )
    }
}

/// One declared tool as a `SimpleTool` registration.
fn gen_tool(tool: &ToolSpec) -> String {
    let mut out = String::new();
    let description = if tool.description.is_empty() {
        format!("Tool '{}'", tool.name)
    } else {
        tool.description.clone()
    };
    let params = match &tool.parameters {
        Some(schema) => format!("Some(json!({}))", compact(schema)),
        None => "None".to_string(),
    };
    let writes_state = !tool.set_state.is_empty();
    if writes_state {
        out.push_str("    {\n        let state = state.clone();\n");
    } else {
        out.push_str("    {\n");
    }
    let _ = writeln!(
        out,
        "        tools.register(SimpleTool::new(\n            {},\n            {},\n            {params},",
        rust_str(&tool.name),
        rust_str(&description),
    );
    if writes_state {
        out.push_str(
            "            move |_args| {\n                let state = state.clone();\n                async move {\n",
        );
    } else {
        out.push_str("            move |_args| async move {\n");
    }
    if let Some(http) = &tool.http {
        let _ = writeln!(
            out,
            "                    // HTTP binding: {} {} — replace with your client of choice.",
            http.method, http.url
        );
    }
    for (key, value) in &tool.set_state {
        let _ = writeln!(
            out,
            "                    let _ = state.set({}, json!({}));",
            rust_str(key),
            compact(value)
        );
    }
    let response = tool
        .response
        .clone()
        .unwrap_or_else(|| serde_json::json!({"ok": true}));
    if writes_state {
        let _ = writeln!(out, "                    Ok(json!({}))", compact(&response));
        out.push_str("                }\n            },\n        ));\n    }\n");
    } else {
        let _ = writeln!(out, "                Ok(json!({}))", compact(&response));
        out.push_str("            },\n        ));\n    }\n");
    }
    out
}

/// The flow as its builder chain.
fn gen_flow(flow: &Flow) -> String {
    let mut out = String::from("    let flow = Flow::new()\n");
    for step in &flow.steps {
        let _ = writeln!(out, "        .step({})", rust_str(&step.id));
        for dep in &step.after {
            let _ = writeln!(out, "        .after({})", rust_str(dep));
        }
        if let Some(posture) = &step.posture {
            let _ = writeln!(out, "        .posture({})", rust_str(posture));
        }
        if let Some(ground) = &step.ground {
            let _ = writeln!(out, "        .ground({})", rust_str(ground));
        }
        if !step.allow.is_empty() {
            let _ = writeln!(out, "        .allow({})", str_array(&step.allow));
        }
        if !step.deny.is_empty() {
            let _ = writeln!(out, "        .deny({})", str_array(&step.deny));
        }
        if let Some(gate) = &step.gate {
            let _ = writeln!(out, "        .gate({})", gen_guard(gate));
        }
        if step.terminal {
            out.push_str("        .terminal()\n");
        }
        if let Some(done) = &step.done {
            let _ = writeln!(out, "        .done({})", gen_guard(done));
        }
    }
    for constraint in &flow.constraints {
        match constraint {
            Constraint::Once(tool) => {
                let _ = writeln!(out, "        .once({})", rust_str(tool));
            }
            Constraint::Before(a, b) => {
                let _ = writeln!(out, "        .before({}, {})", rust_str(a), rust_str(b));
            }
            Constraint::NeverUntil { tool, until } => {
                let _ = writeln!(
                    out,
                    "        .never({}).until({})",
                    rust_str(tool),
                    gen_guard(until)
                );
            }
            Constraint::Require(steps) => {
                let _ = writeln!(out, "        .require({})", str_array(steps));
            }
        }
    }
    if !flow.ambient.is_empty() {
        let _ = writeln!(out, "        .ambient({})", str_array(&flow.ambient));
    }
    for tool in &flow.confirm_tools {
        let _ = writeln!(
            out,
            "        // confirm-gated: {} (see Per-Tool Policies)",
            tool
        );
    }
    out.push_str("        .build()\n        .expect(\"validated in the Flow Studio\");\n");
    out
}

/// A guard as its constructor expression.
fn gen_guard(guard: &Guard) -> String {
    match guard {
        Guard::Spec(pred) => gen_pred(pred),
        Guard::Custom(_) => "Guard::custom(|_| todo!(\"custom guard\"))".to_string(),
    }
}

fn gen_pred(pred: &Pred) -> String {
    match pred {
        Pred::Always => "Guard::always()".to_string(),
        Pred::IsTrue(key) => format!("Guard::is_true({})", rust_str(key)),
        Pred::IsSet(key) => format!("Guard::is_set({})", rust_str(key)),
        Pred::Eq(key, value) => format!("Guard::eq({}, json!({}))", rust_str(key), compact(value)),
        Pred::Captured(fields) => format!("Guard::captured({})", str_array(fields)),
        Pred::CalledOk(tool) => format!("Guard::called_ok({})", rust_str(tool)),
        Pred::Done(step) => format!("Guard::done({})", rust_str(step)),
        Pred::All(preds) => format!(
            "Guard::all([{}])",
            preds.iter().map(gen_pred).collect::<Vec<_>>().join(", ")
        ),
        Pred::Any(preds) => format!(
            "Guard::any([{}])",
            preds.iter().map(gen_pred).collect::<Vec<_>>().join(", ")
        ),
        Pred::Not(pred) => format!("Guard::not({})", gen_pred(pred)),
    }
}

fn gen_extract(extract: &super::ExtractSpec) -> String {
    let mut out = String::new();
    out.push_str("        .extractor(Arc::new(\n");
    let _ = writeln!(
        out,
        "            LlmExtractor::new(\n                {}.to_string(),\n                \
         Arc::new(GeminiLlm::new(Default::default())),\n                {}.to_string(),\n                {},\n            )",
        rust_str(&extract.name),
        rust_str(&extract.instruction),
        extract.window
    );
    let _ = writeln!(
        out,
        "            .with_schema(json!({}))",
        compact(&extract.schema)
    );
    let trigger = match extract.trigger {
        TriggerSpec::EveryTurn => "EveryTurn",
        TriggerSpec::AfterToolCall => "AfterToolCall",
        TriggerSpec::OnGenerationComplete => "OnGenerationComplete",
        TriggerSpec::OnPhaseChange => "OnPhaseChange",
    };
    let _ = writeln!(
        out,
        "            .with_trigger(ExtractionTrigger::{trigger})"
    );
    if !extract.promote.is_empty() {
        out.push_str("            .with_promotions(vec![\n");
        for promote in &extract.promote {
            let ctor = match promote.policy {
                PromotePolicy::KeepKnown => "keep_known",
                PromotePolicy::Overwrite => "overwrite",
                PromotePolicy::TrueOnly => "true_only",
                PromotePolicy::NonEmpty => "non_empty",
            };
            let mut rule = format!("FieldPromotion::{ctor}({})", rust_str(&promote.field));
            if let Some(to) = &promote.to {
                let _ = write!(rule, ".to({})", rust_str(to));
            }
            let _ = writeln!(out, "                {rule},");
        }
        out.push_str("            ])\n");
    }
    out.push_str("        ))\n");
    out
}

fn gen_phase(phase: &super::PhaseSpec) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "        .phase({})", rust_str(&phase.name));
    if let Some(instruction) = &phase.instruction {
        let _ = writeln!(out, "            .instruction({})", rust_str(instruction));
    }
    if !phase.tools.is_empty() {
        let owned: Vec<String> = phase
            .tools
            .iter()
            .map(|t| format!("{}.into()", rust_str(t)))
            .collect();
        let _ = writeln!(out, "            .tools(vec![{}])", owned.join(", "));
    }
    if !phase.needs.is_empty() {
        let _ = writeln!(out, "            .needs(&{})", str_slice(&phase.needs));
    }
    if let Some(prompt) = phase.prompt_on_enter {
        let _ = writeln!(out, "            .prompt_on_enter({prompt})");
    }
    for transition in &phase.transitions {
        let guard = gen_guard(&transition.when);
        let _ = writeln!(
            out,
            "            .transition({}, move |s: &State| {guard}.eval_state(s))",
            rust_str(&transition.to)
        );
    }
    if !phase.on_enter.is_empty() {
        out.push_str("            .on_enter(move |state, _writer| async move {\n");
        for effect in &phase.on_enter {
            match effect {
                EffectSpec::Set(map) => {
                    for (key, value) in map {
                        let _ = writeln!(
                            out,
                            "                let _ = state.set({}, json!({}));",
                            rust_str(key),
                            compact(value)
                        );
                    }
                }
                EffectSpec::Context(text) => {
                    let _ = writeln!(
                        out,
                        "                let _ = _writer.send_client_content(vec![Content::model({})], false).await;",
                        rust_str(text)
                    );
                }
            }
        }
        out.push_str("            })\n");
    }
    if phase.terminal {
        out.push_str("            .terminal()\n");
    }
    out.push_str("            .done()\n");
    out
}

fn gen_watch(watch: &super::WatchSpec) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "        .watch({})", rust_str(&watch.key));
    let condition = match &watch.condition {
        WatchCondition::Changed => "            .changed()".to_string(),
        WatchCondition::ChangedTo(value) => {
            format!("            .changed_to(json!({}))", compact(value))
        }
        WatchCondition::CrossedAbove(threshold) => {
            format!("            .crossed_above({threshold:?})")
        }
        WatchCondition::CrossedBelow(threshold) => {
            format!("            .crossed_below({threshold:?})")
        }
        WatchCondition::BecameTrue => "            .became_true()".to_string(),
        WatchCondition::BecameFalse => "            .became_false()".to_string(),
    };
    let _ = writeln!(out, "{condition}");
    out.push_str("            .then(move |_old, _new, state| async move {\n");
    for (key, value) in &watch.set {
        let _ = writeln!(
            out,
            "                let _ = state.set({}, json!({}));",
            rust_str(key),
            compact(value)
        );
    }
    out.push_str("            })\n");
    out
}

/// A Rust string literal for `s`.
fn rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c if c.is_control() => {
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// `["a", "b"]` — an array literal of string literals.
fn str_array(items: &[String]) -> String {
    format!(
        "[{}]",
        items
            .iter()
            .map(|s| rust_str(s))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

/// `["a", "b"]` for `&[&str]` positions.
fn str_slice(items: &[String]) -> String {
    str_array(items)
}

/// Compact JSON — valid `json!` macro input.
fn compact(value: &Value) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "null".to_string())
}

#[cfg(test)]
mod tests {
    use super::super::SessionSpec;
    use serde_json::json;

    fn spec() -> SessionSpec {
        SessionSpec::from_value(json!({
            "name": "collections",
            "instruction": "Collect payments.",
            "greeting": "Say hello.",
            "tools": [
                {"name": "verify_identity", "description": "Verify the caller.",
                 "set_state": {"identity_verified": true}},
                {"name": "charge_card", "response": {"charged": true}}
            ],
            "extract": [{
                "name": "ptp", "instruction": "Extract the promise to pay.",
                "schema": {"type": "object"},
                "promote": [{"field": "ptp_amount"}]
            }],
            "phases": [{"name": "greet", "instruction": "Welcome.",
                        "transitions": [{"to": "main", "when": {"is_true": "greeted"}}]},
                       {"name": "main"}],
            "initial_phase": "greet",
            "watch": [{"key": "risk", "condition": {"crossed_above": 0.9},
                       "set": {"alert": true}}],
            "flow": {
                "steps": [
                    {"id": "verify", "posture": "Verify.", "allow": ["verify_identity"],
                     "done": {"is_true": "identity_verified"}},
                    {"id": "pay", "after": ["verify"],
                     "gate": {"all": [{"captured": ["ptp_amount"]},
                                       {"not": {"is_true": "disputed"}}]},
                     "allow": ["charge_card"], "done": {"called_ok": "charge_card"}}
                ],
                "constraints": [
                    {"once": "charge_card"},
                    {"never_until": {"tool": "charge_card",
                                     "until": {"is_true": "identity_verified"}}},
                    {"require": ["pay"]}
                ]
            }
        }))
        .expect("parses")
    }

    #[test]
    fn generated_main_contains_the_full_chain() {
        let code = spec().to_rust();
        for fragment in [
            "let flow = Flow::new()",
            ".step(\"verify\")",
            ".done(Guard::is_true(\"identity_verified\"))",
            ".gate(Guard::all([Guard::captured([\"ptp_amount\"]), Guard::not(Guard::is_true(\"disputed\"))]))",
            ".never(\"charge_card\").until(Guard::is_true(\"identity_verified\"))",
            ".once(\"charge_card\")",
            ".require([\"pay\"])",
            "tools.register(SimpleTool::new(",
            "state.set(\"identity_verified\", json!(true))",
            "LlmExtractor::new(",
            "FieldPromotion::keep_known(\"ptp_amount\")",
            ".phase(\"greet\")",
            ".transition(\"main\", move |s: &State| Guard::is_true(\"greeted\").eval_state(s))",
            ".watch(\"risk\")",
            ".crossed_above(0.9)",
            ".connect_from_env()",
            "session.send_text(line.trim()).await?",
        ] {
            assert!(code.contains(fragment), "missing fragment: {fragment}\n---\n{code}");
        }
    }

    #[test]
    fn audio_specs_generate_talk_and_voice_feature() {
        let mut audio = spec();
        audio.modality = super::super::SpecModality::Audio;
        audio.voice = Some("Kore".into());
        let code = audio.to_rust();
        assert!(code.contains(".voice(Voice::Kore)"));
        assert!(code.contains("session.talk().await?"));
        assert!(audio.to_cargo_toml().contains("voice-io"));
    }

    #[test]
    fn string_escaping_is_sound() {
        assert_eq!(super::rust_str("say \"hi\"\n"), "\"say \\\"hi\\\"\\n\"");
    }
}
