//! Golden-wire protocol tests.
//!
//! The Gemini Live wire format *will* drift as Google ships new API versions;
//! these tests make staleness obvious instead of silently wrong.
//!
//! Two directions, two disciplines:
//!
//! - **Client → server** (setup, realtime input, client content, tool
//!   responses): messages our code *generates*. Each test serializes a real
//!   config/command and compares against a checked-in fixture byte-for-byte
//!   (as canonical JSON). To bless intentional protocol changes:
//!   `GOLDEN_BLESS=1 cargo test -p gemini-genai-rs --test golden_wire`
//!   then review the fixture diff like any code change.
//! - **Server → client** (serverContent, toolCall, goAway, …): messages our
//!   code *parses*. Fixtures are hand-written captures of documented server
//!   frames; tests assert they parse into the right `ServerMessage` variant
//!   with the right fields. These fixtures are never regenerated by code —
//!   they are the contract.
//!
//! Platform differences (Google AI vs Vertex AI) are pinned explicitly:
//! model URI shape, `behavior` stripping in tool declarations, `thinkingConfig`
//! stripping, and `scheduling` stripping on tool responses.

use gemini_genai_rs::protocol::messages::ServerMessage;
use gemini_genai_rs::protocol::types::*;
use gemini_genai_rs::session::SessionCommand;
use gemini_genai_rs::transport::codec::{Codec, JsonCodec};

use serde_json::{Value, json};
use std::path::PathBuf;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/wire")
        .join(name)
}

/// Compare generated JSON against a checked-in fixture (canonical `Value`
/// equality — key order is irrelevant, missing/extra fields are not).
fn assert_golden(name: &str, actual: &Value) {
    let path = fixture_path(name);
    if std::env::var_os("GOLDEN_BLESS").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, serde_json::to_string_pretty(actual).unwrap()).unwrap();
        return;
    }
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing fixture {name} ({e}); run with GOLDEN_BLESS=1"));
    let expected: Value = serde_json::from_str(&raw).unwrap();
    assert_eq!(
        &expected, actual,
        "wire drift in {name}.\n  expected (fixture): {expected}\n  actual (generated): {actual}\n\
         If this change is intentional, re-bless with GOLDEN_BLESS=1 and review the diff."
    );
}

fn load_fixture(name: &str) -> String {
    std::fs::read_to_string(fixture_path(name)).unwrap()
}

/// A representative full-featured config: tools (function with NonBlocking
/// behavior + google_search), thinking, voice, transcription, resumption.
fn rich_config(mut config: SessionConfig) -> SessionConfig {
    config = config
        .model(ModelId::from_static("models/gemini-2.0-flash-live-001"))
        .voice(Voice::Kore)
        .thinking(1024)
        .include_thoughts(true)
        .resume_from("resume-handle-123");
    config.system_instruction = Some(Content {
        role: Some(Role::System),
        parts: vec![Part::text("You are a weather assistant")],
    });
    config.tools = vec![
        Tool::functions(vec![FunctionDeclaration {
            name: "get_weather".into(),
            description: "Get weather for a city".into(),
            parameters: Some(json!({
                "type": "object",
                "properties": {"city": {"type": "string"}},
                "required": ["city"]
            })),
            behavior: Some(FunctionCallingBehavior::NonBlocking),
        }]),
        Tool::google_search(),
    ];
    config.input_audio_transcription = Some(InputAudioTranscription {});
    config.output_audio_transcription = Some(OutputAudioTranscription {});
    config
}

// ─── Client → server: setup ─────────────────────────────────────────────────

#[test]
fn setup_google_ai_golden() {
    let config = rich_config(SessionConfig::new("test-api-key"));
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();

    // Pin the platform-specific shape explicitly before the golden diff so
    // intent survives a re-bless.
    assert_eq!(
        actual["setup"]["model"], "models/gemini-2.0-flash-live-001",
        "Google AI uses the bare models/ URI"
    );
    assert_eq!(
        actual["setup"]["tools"][0]["functionDeclarations"][0]["behavior"], "NON_BLOCKING",
        "Google AI keeps async tool behavior"
    );
    assert!(
        actual["setup"]["generationConfig"]["thinkingConfig"].is_object(),
        "Google AI keeps thinkingConfig"
    );

    assert_golden("setup_google_ai.json", &actual);
}

#[test]
fn setup_vertex_ai_golden() {
    let config = rich_config(SessionConfig::from_vertex(
        "test-project",
        "us-central1",
        "test-token",
    ));
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();

    assert_eq!(
        actual["setup"]["model"],
        "projects/test-project/locations/us-central1/publishers/google/models/gemini-2.0-flash-live-001",
        "Vertex AI uses the fully-qualified publisher URI"
    );
    assert!(
        actual["setup"]["tools"][0]["functionDeclarations"][0]
            .get("behavior")
            .is_none(),
        "Vertex AI must strip behavior (async tools unsupported)"
    );
    assert!(
        actual["setup"]["generationConfig"]
            .get("thinkingConfig")
            .is_none(),
        "Vertex AI must strip thinkingConfig"
    );

    assert_golden("setup_vertex_ai.json", &actual);
}

// ─── Client → server: commands through the codec ────────────────────────────

#[test]
fn realtime_audio_input_golden() {
    let config = SessionConfig::new("test-api-key");
    let bytes = JsonCodec
        .encode_command(&SessionCommand::SendAudio(vec![1, 2, 3, 4].into()), &config)
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert_golden("client_realtime_audio.json", &actual);
}

#[test]
fn client_content_text_golden() {
    let config = SessionConfig::new("test-api-key");
    let bytes = JsonCodec
        .encode_command(&SessionCommand::SendText("Hello".into()), &config)
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert_golden("client_content_text.json", &actual);
}

fn tool_response() -> FunctionResponse {
    FunctionResponse {
        name: "search_kb".into(),
        response: json!({"results": ["a", "b"]}),
        id: Some("call-1".into()),
        scheduling: Some(FunctionResponseScheduling::WhenIdle),
    }
}

#[test]
fn tool_response_google_ai_keeps_scheduling_golden() {
    let config = SessionConfig::new("test-api-key");
    let bytes = JsonCodec
        .encode_command(
            &SessionCommand::SendToolResponse(vec![tool_response()]),
            &config,
        )
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert_eq!(
        actual["toolResponse"]["functionResponses"][0]["scheduling"],
        "WHEN_IDLE"
    );
    assert_golden("client_tool_response_google.json", &actual);
}

#[test]
fn tool_response_vertex_ai_strips_scheduling_golden() {
    let config = SessionConfig::from_vertex("test-project", "us-central1", "test-token");
    let bytes = JsonCodec
        .encode_command(
            &SessionCommand::SendToolResponse(vec![tool_response()]),
            &config,
        )
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert!(
        actual["toolResponse"]["functionResponses"][0]
            .get("scheduling")
            .is_none(),
        "Vertex AI must strip scheduling from tool responses"
    );
    assert_golden("client_tool_response_vertex.json", &actual);
}

// ─── Server → client: hand-written fixtures, parse assertions ───────────────

#[test]
fn parse_setup_complete() {
    let msg = ServerMessage::parse(&load_fixture("server_setup_complete.json")).unwrap();
    match msg {
        ServerMessage::SetupComplete(m) => {
            let res = m.setup_complete.session_resumption.unwrap();
            assert_eq!(res.handle.as_deref(), Some("handle-abc"));
            assert_eq!(res.resumed, Some(true));
        }
        other => panic!("expected SetupComplete, got {other:?}"),
    }
}

#[test]
fn parse_server_content_audio() {
    let msg = ServerMessage::parse(&load_fixture("server_content_audio.json")).unwrap();
    match msg {
        ServerMessage::ServerContent(m) => {
            let parts = m.server_content.model_turn.unwrap().parts;
            match &parts[0] {
                Part::InlineData { inline_data } => {
                    assert_eq!(inline_data.mime_type, "audio/pcm;rate=24000");
                    assert_eq!(inline_data.data, "AQIDBA==");
                }
                other => panic!("expected InlineData part, got {other:?}"),
            }
        }
        other => panic!("expected ServerContent, got {other:?}"),
    }
}

#[test]
fn parse_server_content_text_thought_usage() {
    let msg = ServerMessage::parse(&load_fixture("server_content_text_thought.json")).unwrap();
    match msg {
        ServerMessage::ServerContent(m) => {
            let parts = m.server_content.model_turn.unwrap().parts;
            // Untagged Part decoding: thought parts must NOT collapse into Text.
            assert_eq!(
                parts[0],
                Part::Thought {
                    text: "Considering the forecast sources".into(),
                    thought: true
                }
            );
            assert_eq!(
                parts[1],
                Part::Text {
                    text: "It is sunny.".into()
                }
            );
            assert_eq!(m.server_content.generation_complete, Some(true));
            assert_eq!(m.server_content.turn_complete, Some(true));
            let usage = m.usage_metadata.unwrap();
            assert_eq!(usage.prompt_token_count, Some(10));
            assert_eq!(usage.response_token_count, Some(42));
        }
        other => panic!("expected ServerContent, got {other:?}"),
    }
}

#[test]
fn parse_server_content_transcriptions_and_interruption() {
    let msg = ServerMessage::parse(&load_fixture("server_content_transcription.json")).unwrap();
    match msg {
        ServerMessage::ServerContent(m) => {
            assert_eq!(
                m.server_content
                    .input_transcription
                    .unwrap()
                    .text
                    .as_deref(),
                Some("what's the weather")
            );
            assert_eq!(
                m.server_content
                    .output_transcription
                    .unwrap()
                    .text
                    .as_deref(),
                Some("It is sunny")
            );
            assert_eq!(m.server_content.interrupted, Some(true));
        }
        other => panic!("expected ServerContent, got {other:?}"),
    }
}

#[test]
fn parse_tool_call() {
    let msg = ServerMessage::parse(&load_fixture("server_tool_call.json")).unwrap();
    match msg {
        ServerMessage::ToolCall(m) => {
            let calls = m.tool_call.function_calls;
            assert_eq!(calls.len(), 2);
            assert_eq!(calls[0].name, "get_weather");
            assert_eq!(calls[0].id.as_deref(), Some("call-1"));
            assert_eq!(calls[0].args["city"], "Paris");
            assert_eq!(calls[1].name, "get_time");
        }
        other => panic!("expected ToolCall, got {other:?}"),
    }
}

#[test]
fn parse_tool_call_cancellation() {
    // Routing trap pinned: "toolCallCancellation" contains "toolCall" as a
    // substring — the parser must check cancellation first.
    let msg = ServerMessage::parse(&load_fixture("server_tool_call_cancellation.json")).unwrap();
    match msg {
        ServerMessage::ToolCallCancellation(m) => {
            assert_eq!(m.tool_call_cancellation.ids, vec!["call-1", "call-2"]);
        }
        other => panic!("expected ToolCallCancellation, got {other:?}"),
    }
}

#[test]
fn parse_go_away() {
    let msg = ServerMessage::parse(&load_fixture("server_go_away.json")).unwrap();
    match msg {
        ServerMessage::GoAway(m) => {
            assert_eq!(
                m.go_away.time_left,
                Some(std::time::Duration::from_secs(30))
            );
        }
        other => panic!("expected GoAway, got {other:?}"),
    }
}

#[test]
fn parse_session_resumption_update() {
    let msg = ServerMessage::parse(&load_fixture("server_session_resumption_update.json")).unwrap();
    match msg {
        ServerMessage::SessionResumptionUpdate(m) => {
            let p = m.session_resumption_update;
            assert_eq!(p.new_handle.as_deref(), Some("handle-next"));
            assert_eq!(p.resumable, Some(true));
            assert_eq!(p.last_consumed_client_message_index.as_deref(), Some("17"));
        }
        other => panic!("expected SessionResumptionUpdate, got {other:?}"),
    }
}

#[test]
fn parse_unknown_is_forward_compatible() {
    let msg =
        ServerMessage::parse(r#"{"someFutureMessage": {"field": 1}}"#).expect("must not error");
    match msg {
        ServerMessage::Unknown(v) => assert_eq!(v["someFutureMessage"]["field"], 1),
        other => panic!("expected Unknown, got {other:?}"),
    }
}

// ─── Catalog: model/voice wire names ────────────────────────────────────────

#[test]
fn model_catalog_wire_names() {
    let cases = [
        (
            ModelId::from_static("models/gemini-2.0-flash-live-001"),
            "models/gemini-2.0-flash-live-001",
        ),
        (
            ModelId::LIVE_2_5_FLASH_NATIVE_AUDIO,
            "models/gemini-live-2.5-flash-native-audio",
        ),
        (
            ModelId::new("models/gemini-9.9-future"),
            "models/gemini-9.9-future",
        ),
    ];
    for (model, wire) in cases {
        assert_eq!(model.to_string(), wire);
        // The serde form must match Display — both feed the wire.
        assert_eq!(serde_json::to_value(&model).unwrap(), json!(wire));
    }
    // Custom is the forward-compatibility escape hatch: unknown strings must
    // round-trip through deserialization instead of failing.
    let parsed: ModelId = serde_json::from_value(json!("models/not-yet-invented")).unwrap();
    assert_eq!(parsed, ModelId::new("models/not-yet-invented"));
}

#[test]
fn voice_custom_escape_hatch() {
    let parsed: Voice = serde_json::from_value(json!("BrandNewVoice")).unwrap();
    assert_eq!(parsed, Voice::Custom("BrandNewVoice".into()));
}
