//! Golden-wire protocol tests.
//!
//! The Gemini Live wire format *will* drift as Google ships new API versions;
//! these tests make staleness obvious instead of silently wrong.
//!
//! Two directions, two disciplines:
//!
//! - **Client → server** (setup, realtime input, client content, tool
//!   responses): messages our code *generates*. Each test serializes a real
//!   config/command and compares against a checked-in fixture byte-for-byte
//!   (as canonical JSON). To bless intentional protocol changes:
//!   `GOLDEN_BLESS=1 cargo test -p gemini-genai-rs --test golden_wire`
//!   then review the fixture diff like any code change.
//! - **Server → client** (serverContent, toolCall, goAway, …): messages our
//!   code *parses*. Fixtures are hand-written captures of documented server
//!   frames; tests assert they parse into the right `ServerMessage` variant
//!   with the right fields. These fixtures are never regenerated by code —
//!   they are the contract.
//!
//! Platform differences (Google AI vs Vertex AI) are pinned explicitly:
//! model URI shape, `behavior` stripping in tool declarations, `thinkingConfig`
//! stripping, and `scheduling` stripping on tool responses.

use gemini_genai_rs::protocol::messages::ServerMessage;
use gemini_genai_rs::protocol::types::*;
use gemini_genai_rs::session::SessionCommand;
use gemini_genai_rs::transport::codec::{Codec, JsonCodec};

use serde_json::{Value, json};
use std::path::PathBuf;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/wire")
        .join(name)
}

/// Compare generated JSON against a checked-in fixture (canonical `Value`
/// equality — key order is irrelevant, missing/extra fields are not).
fn assert_golden(name: &str, actual: &Value) {
    let path = fixture_path(name);
    if std::env::var_os("GOLDEN_BLESS").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, serde_json::to_string_pretty(actual).unwrap()).unwrap();
        return;
    }
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing fixture {name} ({e}); run with GOLDEN_BLESS=1"));
    let expected: Value = serde_json::from_str(&raw).unwrap();
    assert_eq!(
        &expected, actual,
        "wire drift in {name}.\n  expected (fixture): {expected}\n  actual (generated): {actual}\n\
         If this change is intentional, re-bless with GOLDEN_BLESS=1 and review the diff."
    );
}

fn load_fixture(name: &str) -> String {
    std::fs::read_to_string(fixture_path(name)).unwrap()
}

/// A representative full-featured config: tools (function with NonBlocking
/// behavior + google_search), thinking, voice, transcription, resumption.
fn rich_config(mut config: SessionConfig) -> SessionConfig {
    config = config
        .model(ModelId::from_static("models/gemini-2.0-flash-live-001"))
        .voice(Voice::Kore)
        .thinking(1024)
        .include_thoughts(true)
        .resume_from("resume-handle-123");
    config.system_instruction = Some(Content {
        role: Some(Role::System),
        parts: vec![Part::text("You are a weather assistant")],
    });
    config.tools = vec![
        Tool::functions(vec![FunctionDeclaration {
            name: "get_weather".into(),
            description: "Get weather for a city".into(),
            parameters: Some(json!({
                "type": "object",
                "properties": {"city": {"type": "string"}},
                "required": ["city"]
            })),
            behavior: Some(FunctionCallingBehavior::NonBlocking),
        }]),
        Tool::google_search(),
    ];
    config.input_audio_transcription = Some(InputAudioTranscription::default());
    config.output_audio_transcription = Some(OutputAudioTranscription::default());
    config
}

// ─── Client → server: setup ─────────────────────────────────────────────────

#[test]
fn setup_google_ai_golden() {
    let config = rich_config(SessionConfig::new("test-api-key"));
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();

    // Pin the platform-specific shape explicitly before the golden diff so
    // intent survives a re-bless.
    assert_eq!(
        actual["setup"]["model"], "models/gemini-2.0-flash-live-001",
        "Google AI uses the bare models/ URI"
    );
    assert_eq!(
        actual["setup"]["tools"][0]["functionDeclarations"][0]["behavior"], "NON_BLOCKING",
        "Google AI keeps async tool behavior"
    );
    assert!(
        actual["setup"]["generationConfig"]["thinkingConfig"].is_object(),
        "Google AI keeps thinkingConfig"
    );

    assert_golden("setup_google_ai.json", &actual);
}

#[test]
fn setup_vertex_ai_golden() {
    let config = rich_config(SessionConfig::from_vertex(
        "test-project",
        "us-central1",
        "test-token",
    ));
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();

    assert_eq!(
        actual["setup"]["model"],
        "projects/test-project/locations/us-central1/publishers/google/models/gemini-2.0-flash-live-001",
        "Vertex AI uses the fully-qualified publisher URI"
    );
    assert!(
        actual["setup"]["tools"][0]["functionDeclarations"][0]
            .get("behavior")
            .is_none(),
        "Vertex AI must strip behavior (async tools unsupported)"
    );
    assert!(
        actual["setup"]["generationConfig"]
            .get("thinkingConfig")
            .is_none(),
        "Vertex AI must strip thinkingConfig"
    );

    assert_golden("setup_vertex_ai.json", &actual);
}

// ─── Client → server: commands through the codec ────────────────────────────

#[test]
fn realtime_audio_input_golden() {
    let config = SessionConfig::new("test-api-key");
    let bytes = JsonCodec
        .encode_command(&SessionCommand::SendAudio(vec![1, 2, 3, 4].into()), &config)
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert_golden("client_realtime_audio.json", &actual);
}

#[test]
fn client_content_text_golden() {
    let config = SessionConfig::new("test-api-key");
    let bytes = JsonCodec
        .encode_command(&SessionCommand::SendText("Hello".into()), &config)
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert_golden("client_content_text.json", &actual);
}

fn tool_response() -> FunctionResponse {
    FunctionResponse {
        name: "search_kb".into(),
        response: json!({"results": ["a", "b"]}),
        id: Some("call-1".into()),
        scheduling: Some(FunctionResponseScheduling::WhenIdle),
    }
}

#[test]
fn tool_response_google_ai_keeps_scheduling_golden() {
    let config = SessionConfig::new("test-api-key");
    let bytes = JsonCodec
        .encode_command(
            &SessionCommand::SendToolResponse(vec![tool_response()]),
            &config,
        )
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert_eq!(
        actual["toolResponse"]["functionResponses"][0]["scheduling"],
        "WHEN_IDLE"
    );
    assert_golden("client_tool_response_google.json", &actual);
}

#[test]
fn tool_response_vertex_ai_strips_scheduling_golden() {
    let config = SessionConfig::from_vertex("test-project", "us-central1", "test-token");
    let bytes = JsonCodec
        .encode_command(
            &SessionCommand::SendToolResponse(vec![tool_response()]),
            &config,
        )
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert!(
        actual["toolResponse"]["functionResponses"][0]
            .get("scheduling")
            .is_none(),
        "Vertex AI must strip scheduling from tool responses"
    );
    assert_golden("client_tool_response_vertex.json", &actual);
}

// ─── Client → server: Gemini 3.8 Live ───────────────────────────────────────

/// Gemini 3.8 Live on Vertex AI, with every setting its guide introduces.
fn gemini_3_8_config() -> SessionConfig {
    let mut config = SessionConfig::from_vertex("test-project", "us-central1", "test-token")
        .model(ModelId::LIVE_3_8)
        .voice(Voice::Custom("Aoede".into()))
        .avatar(AvatarConfig::prebuilt("Ben"))
        .input_transcription_config(
            AudioTranscriptionConfig::default().language_codes(["en-US", "es-US"]),
        )
        .custom_vocabulary(["ORD-8472", "Express Shipping"])
        .output_transcription(true)
        .media_resolution(MediaResolution::Low)
        .transparent_resumption()
        .explicit_vad_signal(true)
        .initial_history_in_client_content(true)
        // Settings the 3.8 guide says not to send: always on, or unsupported.
        .affective_dialog(true)
        .proactive_audio(true)
        .thinking(512);
    config.tools = vec![Tool::functions(vec![FunctionDeclaration {
        name: "lookup_order_status".into(),
        description: "Fetches real-time shipping status for a customer order ID.".into(),
        parameters: Some(json!({
            "type": "object",
            "properties": {"order_id": {"type": "string"}},
            "required": ["order_id"]
        })),
        behavior: Some(FunctionCallingBehavior::Blocking),
    }])];
    config
}

#[test]
fn setup_vertex_gemini_3_8_live_golden() {
    let config = gemini_3_8_config();
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();
    let setup = &actual["setup"];

    assert_eq!(
        setup["model"],
        "projects/test-project/locations/us-central1/publishers/google/models/gemini-3.8-live"
    );
    // Field names and placement as the Gen AI SDK's Vertex converter sends them.
    assert_eq!(
        setup["generationConfig"]["responseModalities"],
        json!(["VIDEO"])
    );
    assert_eq!(setup["avatarConfig"], json!({"avatarName": "Ben"}));
    assert_eq!(
        setup["inputAudioTranscription"],
        json!({
            "languageCodes": ["en-US", "es-US"],
            "customVocabulary": ["ORD-8472", "Express Shipping"],
        })
    );
    assert_eq!(setup["outputAudioTranscription"], json!({}));
    assert_eq!(
        setup["generationConfig"]["mediaResolution"],
        "MEDIA_RESOLUTION_LOW"
    );
    assert_eq!(setup["sessionResumption"], json!({"transparent": true}));
    assert_eq!(setup["explicitVadSignal"], true);
    assert_eq!(
        setup["historyConfig"],
        json!({"initialHistoryInClientContent": true})
    );
    // 3.8 on Vertex takes blocking/non-blocking tool behavior.
    assert_eq!(
        setup["tools"][0]["functionDeclarations"][0]["behavior"],
        "BLOCKING"
    );
    // "Do not pass enable_affective_dialog or proactivity"; thinking is unsupported.
    assert!(
        setup["generationConfig"]
            .get("enableAffectiveDialog")
            .is_none()
    );
    assert!(setup.get("proactivity").is_none());
    assert!(setup["generationConfig"].get("thinkingConfig").is_none());
    assert_eq!(
        config.ignored_settings(),
        ["thinkingConfig", "enableAffectiveDialog", "proactivity"]
    );

    assert_golden("setup_vertex_gemini_3_8_live.json", &actual);
}

/// What the live Google AI endpoint refuses, measured on 2026-09-25 with
/// `gemini-3.8-live` (and `proactivity` / `transparent` with 2.5 too): each
/// of these closed the setup with 1007 "Unknown name … Cannot find field".
#[test]
fn google_ai_leaves_off_fields_its_setup_does_not_have() {
    let config = SessionConfig::new("key")
        .model(ModelId::LIVE_3_8)
        .proactive_audio(true)
        .transparent_resumption()
        .explicit_vad_signal(true)
        .avatar(AvatarConfig::prebuilt("Ben").bitrates(64_000, 1_000_000));
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();
    let setup = &actual["setup"];
    assert!(setup.get("proactivity").is_none());
    assert!(setup.get("explicitVadSignal").is_none());
    assert_eq!(setup["sessionResumption"], json!({}));
    assert_eq!(
        setup["avatarConfig"],
        json!({"audioBitrateBps": 64_000, "videoBitrateBps": 1_000_000})
    );
    assert_eq!(
        config.ignored_settings(),
        [
            "proactivity",
            "sessionResumption.transparent",
            "avatarConfig.avatarName",
            "explicitVadSignal"
        ]
    );
    // Proactivity is refused on Google AI for every model, not just 3.8.
    let older = SessionConfig::new("key")
        .model(ModelId::FLASH_2_5_NATIVE_AUDIO_LATEST)
        .proactive_audio(true);
    assert!(
        serde_json::from_str::<Value>(&older.to_setup_json()).unwrap()["setup"]
            .get("proactivity")
            .is_none()
    );
    assert_eq!(older.ignored_settings(), ["proactivity"]);
}

#[test]
fn extended_thinking_keeps_its_required_thinking_level() {
    for config in [
        SessionConfig::new("key"),
        SessionConfig::from_vertex("p", "us-central1", "t"),
    ] {
        let config = config
            .model(ModelId::LIVE_3_8_EXTENDED_THINKING)
            .thinking_level(ThinkingLevel::Low)
            .affective_dialog(true);
        let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();
        let generation = &actual["setup"]["generationConfig"];
        assert_eq!(
            generation["thinkingConfig"],
            json!({"thinkingLevel": "LOW"})
        );
        assert!(generation.get("enableAffectiveDialog").is_none());
    }
    // Plain 3.8 refuses a thinking level: it goes with the rest of thinkingConfig.
    let plain = SessionConfig::new("key")
        .model(ModelId::LIVE_3_8)
        .thinking_level(ThinkingLevel::Low);
    let actual: Value = serde_json::from_str(&plain.to_setup_json()).unwrap();
    assert!(
        actual["setup"]["generationConfig"]
            .get("thinkingConfig")
            .is_none()
    );
    assert_eq!(plain.ignored_settings(), ["thinkingConfig"]);
}

#[test]
fn explicit_vad_signal_is_vertex_only() {
    let config = SessionConfig::new("key").explicit_vad_signal(true);
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();
    assert!(actual["setup"].get("explicitVadSignal").is_none());
    assert_eq!(config.ignored_settings(), ["explicitVadSignal"]);
}

#[test]
fn tool_response_vertex_gemini_3_8_keeps_scheduling() {
    let config = SessionConfig::from_vertex("test-project", "us-central1", "test-token")
        .model(ModelId::LIVE_3_8);
    let bytes = JsonCodec
        .encode_command(
            &SessionCommand::SendToolResponse(vec![tool_response()]),
            &config,
        )
        .unwrap();
    let actual: Value = serde_json::from_slice(&bytes).unwrap();
    assert_eq!(
        actual["toolResponse"]["functionResponses"][0]["scheduling"],
        "WHEN_IDLE"
    );
}

#[test]
fn vad_sensitivity_uses_per_field_wire_enums() {
    let config = SessionConfig::new("key").server_vad(AutomaticActivityDetection {
        disabled: None,
        start_of_speech_sensitivity: Some(Sensitivity::SensitivityHigh),
        end_of_speech_sensitivity: Some(Sensitivity::SensitivityLow),
        prefix_padding_ms: None,
        silence_duration_ms: Some(400),
    });
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();
    assert_eq!(
        actual["setup"]["realtimeInputConfig"]["automaticActivityDetection"],
        json!({
            "startOfSpeechSensitivity": "START_SENSITIVITY_HIGH",
            "endOfSpeechSensitivity": "END_SENSITIVITY_LOW",
            "silenceDurationMs": 400,
        })
    );
    // A level the wire has no value for falls back to the server default.
    let medium = AutomaticActivityDetection {
        disabled: None,
        start_of_speech_sensitivity: Some(Sensitivity::SensitivityMedium),
        end_of_speech_sensitivity: None,
        prefix_padding_ms: None,
        silence_duration_ms: None,
    };
    assert_eq!(
        serde_json::to_value(&medium).unwrap(),
        json!({"startOfSpeechSensitivity": "START_SENSITIVITY_UNSPECIFIED"})
    );
    let back: AutomaticActivityDetection =
        serde_json::from_value(json!({"startOfSpeechSensitivity": "START_SENSITIVITY_HIGH"}))
            .unwrap();
    assert_eq!(
        back.start_of_speech_sensitivity,
        Some(Sensitivity::SensitivityHigh)
    );
}

#[test]
fn media_resolution_reads_old_and_new_names() {
    for raw in ["MEDIA_RESOLUTION_HIGH", "HIGH"] {
        let parsed: MediaResolution = serde_json::from_value(json!(raw)).unwrap();
        assert_eq!(parsed, MediaResolution::High);
    }
}

#[test]
fn replicated_voice_and_custom_avatar_wire_shape() {
    let config = SessionConfig::from_vertex("p", "us-central1", "t")
        .model(ModelId::LIVE_3_8)
        .replicated_voice(ReplicatedVoiceConfig::from_sample(
            b"pcm",
            "audio/pcm;rate=24000",
        ))
        .avatar(AvatarConfig::custom(b"png-bytes", "png"));
    let actual: Value = serde_json::from_str(&config.to_setup_json()).unwrap();
    assert_eq!(
        actual["setup"]["generationConfig"]["speechConfig"],
        json!({"voiceConfig": {"replicatedVoiceConfig": {
            "mimeType": "audio/pcm;rate=24000",
            "voiceSampleAudio": "cGNt",
        }}})
    );
    assert_eq!(
        actual["setup"]["avatarConfig"],
        json!({"customizedAvatar": {"imageMimeType": "png", "imageData": "cG5nLWJ5dGVz"}})
    );
}

// ─── Server → client: hand-written fixtures, parse assertions ───────────────

#[test]
fn parse_setup_complete() {
    let msg = ServerMessage::parse(&load_fixture("server_setup_complete.json")).unwrap();
    match msg {
        ServerMessage::SetupComplete(m) => {
            let res = m.setup_complete.session_resumption.unwrap();
            assert_eq!(res.handle.as_deref(), Some("handle-abc"));
            assert_eq!(res.resumed, Some(true));
        }
        other => panic!("expected SetupComplete, got {other:?}"),
    }
}

#[test]
fn parse_server_content_audio() {
    let msg = ServerMessage::parse(&load_fixture("server_content_audio.json")).unwrap();
    match msg {
        ServerMessage::ServerContent(m) => {
            let parts = m.server_content.model_turn.unwrap().parts;
            match &parts[0] {
                Part::InlineData { inline_data } => {
                    assert_eq!(inline_data.mime_type, "audio/pcm;rate=24000");
                    assert_eq!(inline_data.data, "AQIDBA==");
                }
                other => panic!("expected InlineData part, got {other:?}"),
            }
        }
        other => panic!("expected ServerContent, got {other:?}"),
    }
}

#[test]
fn parse_server_content_text_thought_usage() {
    let msg = ServerMessage::parse(&load_fixture("server_content_text_thought.json")).unwrap();
    match msg {
        ServerMessage::ServerContent(m) => {
            let parts = m.server_content.model_turn.unwrap().parts;
            // Untagged Part decoding: thought parts must NOT collapse into Text.
            assert_eq!(
                parts[0],
                Part::Thought {
                    text: "Considering the forecast sources".into(),
                    thought: true
                }
            );
            assert_eq!(
                parts[1],
                Part::Text {
                    text: "It is sunny.".into()
                }
            );
            assert_eq!(m.server_content.generation_complete, Some(true));
            assert_eq!(m.server_content.turn_complete, Some(true));
            let usage = m.usage_metadata.unwrap();
            assert_eq!(usage.prompt_token_count, Some(10));
            assert_eq!(usage.response_token_count, Some(42));
        }
        other => panic!("expected ServerContent, got {other:?}"),
    }
}

#[test]
fn parse_server_content_transcriptions_and_interruption() {
    let msg = ServerMessage::parse(&load_fixture("server_content_transcription.json")).unwrap();
    match msg {
        ServerMessage::ServerContent(m) => {
            assert_eq!(
                m.server_content
                    .input_transcription
                    .unwrap()
                    .text
                    .as_deref(),
                Some("what's the weather")
            );
            assert_eq!(
                m.server_content
                    .output_transcription
                    .unwrap()
                    .text
                    .as_deref(),
                Some("It is sunny")
            );
            assert_eq!(m.server_content.interrupted, Some(true));
        }
        other => panic!("expected ServerContent, got {other:?}"),
    }
}

#[test]
fn parse_tool_call() {
    let msg = ServerMessage::parse(&load_fixture("server_tool_call.json")).unwrap();
    match msg {
        ServerMessage::ToolCall(m) => {
            let calls = m.tool_call.function_calls;
            assert_eq!(calls.len(), 2);
            assert_eq!(calls[0].name, "get_weather");
            assert_eq!(calls[0].id.as_deref(), Some("call-1"));
            assert_eq!(calls[0].args["city"], "Paris");
            assert_eq!(calls[1].name, "get_time");
        }
        other => panic!("expected ToolCall, got {other:?}"),
    }
}

#[test]
fn parse_tool_call_cancellation() {
    // Routing trap pinned: "toolCallCancellation" contains "toolCall" as a
    // substring — the parser must check cancellation first.
    let msg = ServerMessage::parse(&load_fixture("server_tool_call_cancellation.json")).unwrap();
    match msg {
        ServerMessage::ToolCallCancellation(m) => {
            assert_eq!(m.tool_call_cancellation.ids, vec!["call-1", "call-2"]);
        }
        other => panic!("expected ToolCallCancellation, got {other:?}"),
    }
}

#[test]
fn parse_go_away() {
    let msg = ServerMessage::parse(&load_fixture("server_go_away.json")).unwrap();
    match msg {
        ServerMessage::GoAway(m) => {
            assert_eq!(
                m.go_away.time_left,
                Some(std::time::Duration::from_secs(30))
            );
        }
        other => panic!("expected GoAway, got {other:?}"),
    }
}

#[test]
fn parse_session_resumption_update() {
    let msg = ServerMessage::parse(&load_fixture("server_session_resumption_update.json")).unwrap();
    match msg {
        ServerMessage::SessionResumptionUpdate(m) => {
            let p = m.session_resumption_update;
            assert_eq!(p.new_handle.as_deref(), Some("handle-next"));
            assert_eq!(p.resumable, Some(true));
            assert_eq!(p.last_consumed_client_message_index.as_deref(), Some("17"));
        }
        other => panic!("expected SessionResumptionUpdate, got {other:?}"),
    }
}

#[test]
fn parse_session_resumption_update_numeric_index() {
    let msg = ServerMessage::parse(
        r#"{"sessionResumptionUpdate":{"newHandle":"h","resumable":true,"lastConsumedClientMessageIndex":42}}"#,
    )
    .unwrap();
    match msg {
        ServerMessage::SessionResumptionUpdate(m) => assert_eq!(
            m.session_resumption_update
                .last_consumed_client_message_index
                .as_deref(),
            Some("42")
        ),
        other => panic!("expected SessionResumptionUpdate, got {other:?}"),
    }
}

#[test]
fn parse_interaction_status() {
    let msg =
        ServerMessage::parse(r#"{"serverContent":{"interactionStatus":"IN_PROGRESS"}}"#).unwrap();
    match msg {
        ServerMessage::ServerContent(m) => assert_eq!(
            m.server_content.interaction_status.as_deref(),
            Some("IN_PROGRESS")
        ),
        other => panic!("expected ServerContent, got {other:?}"),
    }
}

#[test]
fn parse_voice_activity() {
    use gemini_genai_rs::protocol::messages::VoiceActivityType;
    let msg = ServerMessage::parse(&load_fixture("server_voice_activity.json")).unwrap();
    match msg {
        ServerMessage::VoiceActivity(m) => {
            assert_eq!(
                m.voice_activity.voice_activity_type,
                Some(VoiceActivityType::VoiceActivityStart)
            );
            assert_eq!(m.voice_activity.audio_offset.as_deref(), Some("1.250s"));
        }
        other => panic!("expected VoiceActivity, got {other:?}"),
    }
    // An unknown activity type must not fail the frame.
    let msg =
        ServerMessage::parse(r#"{"voiceActivity":{"voiceActivityType":"SOMETHING_NEW"}}"#).unwrap();
    match msg {
        ServerMessage::VoiceActivity(m) => assert_eq!(
            m.voice_activity.voice_activity_type,
            Some(VoiceActivityType::Unspecified)
        ),
        other => panic!("expected VoiceActivity, got {other:?}"),
    }
}

#[test]
fn parse_unknown_is_forward_compatible() {
    let msg =
        ServerMessage::parse(r#"{"someFutureMessage": {"field": 1}}"#).expect("must not error");
    match msg {
        ServerMessage::Unknown(v) => assert_eq!(v["someFutureMessage"]["field"], 1),
        other => panic!("expected Unknown, got {other:?}"),
    }
}

// ─── Catalog: model/voice wire names ────────────────────────────────────────

#[test]
fn model_catalog_wire_names() {
    let cases = [
        (
            ModelId::from_static("models/gemini-2.0-flash-live-001"),
            "models/gemini-2.0-flash-live-001",
        ),
        (
            ModelId::LIVE_2_5_FLASH_NATIVE_AUDIO,
            "models/gemini-live-2.5-flash-native-audio",
        ),
        (ModelId::LIVE_3_8, "models/gemini-3.8-live"),
        (
            ModelId::new("models/gemini-9.9-future"),
            "models/gemini-9.9-future",
        ),
    ];
    for (model, wire) in cases {
        assert_eq!(model.to_string(), wire);
        // The serde form must match Display — both feed the wire.
        assert_eq!(serde_json::to_value(&model).unwrap(), json!(wire));
    }
    // Custom is the forward-compatibility escape hatch: unknown strings must
    // round-trip through deserialization instead of failing.
    let parsed: ModelId = serde_json::from_value(json!("models/not-yet-invented")).unwrap();
    assert_eq!(parsed, ModelId::new("models/not-yet-invented"));
}

#[test]
fn voice_custom_escape_hatch() {
    let parsed: Voice = serde_json::from_value(json!("BrandNewVoice")).unwrap();
    assert_eq!(parsed, Voice::Custom("BrandNewVoice".into()));
}
