use crate::schema::{AdkSchema, AgentDef, AgentKind, FieldDef, ToolDef};

/// Convert a TypeScript camelCase or PascalCase name to Rust snake_case.
pub fn to_snake_case(name: &str) -> String {
    let mut result = String::new();
    let mut chars = name.chars().peekable();
    let mut prev_was_upper = false;
    let mut prev_was_underscore = true; // treat start as after underscore

    while let Some(c) = chars.next() {
        if c == '_' {
            result.push('_');
            prev_was_upper = false;
            prev_was_underscore = true;
            continue;
        }

        if c.is_uppercase() {
            // Insert underscore before uppercase if:
            // - Not at start and previous char wasn't underscore
            // - AND (previous wasn't uppercase, OR next is lowercase — handles "HTMLParser" -> "html_parser")
            if !prev_was_underscore {
                let next_is_lower = chars.peek().is_some_and(|n| n.is_lowercase());
                if !prev_was_upper || next_is_lower {
                    result.push('_');
                }
            }
            result.push(c.to_lowercase().next().unwrap());
            prev_was_upper = true;
            prev_was_underscore = false;
        } else {
            result.push(c);
            prev_was_upper = false;
            prev_was_underscore = false;
        }
    }

    result
}

/// Convert a TypeScript interface name to a Rust struct name.
///
/// Strips the "Config" suffix if present:
/// - "BaseAgentConfig" -> "BaseAgent"
/// - "LlmAgentConfig" -> "LlmAgent"
/// - "FunctionTool" -> "FunctionTool" (no change)
pub fn to_rust_struct_name(ts_name: &str) -> String {
    ts_name
        .strip_suffix("Config")
        .unwrap_or(ts_name)
        .to_string()
}

/// Return a Rust default expression for a given Rust type.
pub fn rust_default_for_type(rust_type: &str, optional: bool) -> String {
    if optional {
        "None".to_string()
    } else {
        match rust_type {
            "String" => "String::new()".to_string(),
            "bool" => "false".to_string(),
            "f64" => "0.0".to_string(),
            "()" => "()".to_string(),
            t if t.starts_with("Vec<") => "Vec::new()".to_string(),
            _ => "Default::default()".to_string(),
        }
    }
}

/// Return the Rust type for a field, wrapping in `Option<>` if optional.
fn field_rust_type(field: &FieldDef) -> String {
    if field.optional {
        format!("Option<{}>", field.rust_type)
    } else {
        field.rust_type.clone()
    }
}

/// Check if an AgentKind represents a composition agent (Sequential, Parallel, Loop).
fn is_composition_agent(kind: &AgentKind) -> bool {
    matches!(kind, AgentKind::Sequential | AgentKind::Parallel | AgentKind::Loop)
}

/// Generate Rust source code from an `AdkSchema`.
pub fn generate(schema: &AdkSchema) -> String {
    let mut out = String::new();

    // File header
    out.push_str("// AUTO-GENERATED by adk-transpiler -- do not edit manually\n");
    out.push_str(&format!("// Source: {}\n", schema.source.framework));
    out.push_str(&format!(
        "// Generated: {}\n",
        schema.source.extracted_at
    ));
    out.push('\n');

    // Imports
    out.push_str("#![allow(dead_code, unused_imports)]\n\n");
    out.push_str("use std::sync::Arc;\n");
    out.push_str("use async_trait::async_trait;\n");
    out.push('\n');

    // Placeholder trait/type definitions so the generated code compiles standalone
    out.push_str("// -- Placeholder trait and type definitions --\n");
    out.push_str("// Replace these with actual imports from gemini-live-runtime.\n\n");
    out.push_str("#[async_trait]\n");
    out.push_str("pub trait Agent: Send + Sync {\n");
    out.push_str("    fn name(&self) -> &str;\n");
    out.push_str("    async fn run_live(&self, ctx: &mut InvocationContext) -> Result<(), AgentError>;\n");
    out.push_str("}\n\n");
    out.push_str("pub struct InvocationContext;\n");
    out.push_str("#[derive(Debug)] pub struct AgentError;\n\n");

    // Generate agents
    for agent in &schema.agents {
        out.push_str(&generate_agent(agent));
        out.push('\n');
    }

    // Generate tools
    for tool in &schema.tools {
        out.push_str(&generate_tool(tool));
        out.push('\n');
    }

    out
}

/// Generate Rust code for a single agent definition:
/// - Config struct
/// - Default impl
/// - Builder
/// - Wrapper struct
/// - Agent trait impl (for composition agents)
fn generate_agent(agent: &AgentDef) -> String {
    let struct_name = to_rust_struct_name(&agent.name);
    let config_name = format!("{}Config", struct_name);
    let builder_name = format!("{}Builder", struct_name);

    let mut out = String::new();

    // Section separator
    out.push_str(&format!(
        "// ---- {} ----\n\n",
        struct_name
    ));

    // Doc comment
    if let Some(desc) = &agent.description {
        for line in desc.lines() {
            out.push_str(&format!("/// {}\n", line));
        }
    }

    // Filter out the "name" field since we always generate it explicitly.
    let fields: Vec<&FieldDef> = agent
        .fields
        .iter()
        .filter(|f| f.name != "name")
        .collect();

    // --- Config struct ---
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("pub struct {} {{\n", config_name));
    out.push_str("    pub name: String,\n");

    for field in &fields {
        if let Some(desc) = &field.description {
            out.push_str(&format!("    /// {}\n", desc));
        }
        let snake = to_snake_case(&field.name);
        let rtype = field_rust_type(field);
        out.push_str(&format!("    pub {}: {},\n", snake, rtype));
    }

    // Callbacks as comments
    for cb in &agent.callbacks {
        out.push_str(&format!("    // Callback: {}\n", cb.name));
        out.push_str(&format!("    // TS signature: {}\n", cb.ts_signature));
        if let Some(desc) = &cb.description {
            out.push_str(&format!("    // {}\n", desc));
        }
        out.push_str("    // TODO: Implement Rust callback type\n");
    }

    out.push_str("}\n\n");

    // --- Default impl ---
    out.push_str(&format!("impl Default for {} {{\n", config_name));
    out.push_str("    fn default() -> Self {\n");
    out.push_str("        Self {\n");
    out.push_str("            name: String::new(),\n");

    for field in &fields {
        let snake = to_snake_case(&field.name);
        let default = rust_default_for_type(&field.rust_type, field.optional);
        out.push_str(&format!("            {}: {},\n", snake, default));
    }

    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // --- Builder ---
    out.push_str(&format!("pub struct {} {{\n", builder_name));
    out.push_str(&format!("    config: {},\n", config_name));
    out.push_str("}\n\n");

    out.push_str(&format!("impl {} {{\n", builder_name));

    // Builder::new
    out.push_str("    pub fn new(name: impl Into<String>) -> Self {\n");
    out.push_str("        Self {\n");
    out.push_str(&format!("            config: {} {{\n", config_name));
    out.push_str("                name: name.into(),\n");
    out.push_str(&format!(
        "                ..{}::default()\n",
        config_name
    ));
    out.push_str("            },\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    // Builder methods for each field
    for field in &fields {
        let snake = to_snake_case(&field.name);
        if field.optional {
            // For optional fields, the setter takes the inner type
            out.push_str(&format!(
                "    pub fn {}(mut self, value: {}) -> Self {{\n",
                snake, field.rust_type
            ));
            out.push_str(&format!(
                "        self.config.{} = Some(value);\n",
                snake
            ));
        } else {
            out.push_str(&format!(
                "    pub fn {}(mut self, value: {}) -> Self {{\n",
                snake, field.rust_type
            ));
            out.push_str(&format!(
                "        self.config.{} = value;\n",
                snake
            ));
        }
        out.push_str("        self\n");
        out.push_str("    }\n\n");
    }

    // Builder::build
    out.push_str(&format!(
        "    pub fn build(self) -> {} {{\n",
        struct_name
    ));
    out.push_str(&format!(
        "        {} {{ config: self.config }}\n",
        struct_name
    ));
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // --- Wrapper struct ---
    out.push_str(&format!("pub struct {} {{\n", struct_name));
    out.push_str(&format!("    config: {},\n", config_name));
    out.push_str("}\n\n");

    // --- Agent trait impl (for all agents, composition gets todo!, others get comment) ---
    if is_composition_agent(&agent.kind) {
        out.push_str("#[async_trait]\n");
        out.push_str(&format!("impl Agent for {} {{\n", struct_name));
        out.push_str("    fn name(&self) -> &str {\n");
        out.push_str("        &self.config.name\n");
        out.push_str("    }\n\n");
        out.push_str("    async fn run_live(&self, _ctx: &mut InvocationContext) -> Result<(), AgentError> {\n");
        out.push_str("        // Generated stub -- override with actual implementation\n");
        out.push_str(&format!(
            "        todo!(\"{}::run_live\")\n",
            struct_name
        ));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    } else {
        out.push_str(&format!(
            "// Agent trait impl for {} should be provided by the runtime crate.\n\n",
            struct_name
        ));
    }

    out
}

/// Generate Rust code for a tool definition: a params struct with fields.
fn generate_tool(tool: &ToolDef) -> String {
    let struct_name = to_rust_struct_name(&tool.name);

    let mut out = String::new();

    out.push_str(&format!("// ---- {} ----\n\n", struct_name));

    if let Some(desc) = &tool.description {
        for line in desc.lines() {
            out.push_str(&format!("/// {}\n", line));
        }
    }

    out.push_str("#[derive(Debug, Clone, Default)]\n");
    out.push_str(&format!("pub struct {} {{\n", struct_name));

    for field in &tool.fields {
        if let Some(desc) = &field.description {
            out.push_str(&format!("    /// {}\n", desc));
        }
        let snake = to_snake_case(&field.name);
        let rtype = field_rust_type(field);
        out.push_str(&format!("    pub {}: {},\n", snake, rtype));
    }

    out.push_str("}\n\n");

    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::*;

    fn make_agent(
        name: &str,
        kind: AgentKind,
        fields: Vec<FieldDef>,
        callbacks: Vec<CallbackDef>,
    ) -> AgentDef {
        AgentDef {
            name: name.to_string(),
            kind,
            description: Some("Test agent description.".to_string()),
            fields,
            callbacks,
            extends: None,
        }
    }

    fn make_field(name: &str, rust_type: &str, optional: bool) -> FieldDef {
        FieldDef {
            name: name.to_string(),
            ts_type: "string".to_string(),
            rust_type: rust_type.to_string(),
            optional,
            default_value: None,
            description: None,
        }
    }

    fn make_schema_with(agents: Vec<AgentDef>, tools: Vec<ToolDef>) -> AdkSchema {
        AdkSchema {
            source: SourceInfo {
                framework: "adk-js".to_string(),
                source_dir: "/tmp/test".to_string(),
                extracted_at: "2026-03-02T00:00:00Z".to_string(),
            },
            agents,
            tools,
        }
    }

    #[test]
    fn codegen_snake_case_conversion() {
        assert_eq!(to_snake_case("beforeAgentCallback"), "before_agent_callback");
        assert_eq!(to_snake_case("maxIterations"), "max_iterations");
        assert_eq!(to_snake_case("name"), "name");
        assert_eq!(to_snake_case("HTMLParser"), "html_parser");
        assert_eq!(to_snake_case("disallowTransferToParent"), "disallow_transfer_to_parent");
        assert_eq!(to_snake_case("outputKey"), "output_key");
        assert_eq!(to_snake_case("includeContents"), "include_contents");
        assert_eq!(to_snake_case("subAgents"), "sub_agents");
    }

    #[test]
    fn codegen_rust_struct_name() {
        assert_eq!(to_rust_struct_name("BaseAgentConfig"), "BaseAgent");
        assert_eq!(to_rust_struct_name("LlmAgentConfig"), "LlmAgent");
        assert_eq!(to_rust_struct_name("FunctionTool"), "FunctionTool");
        assert_eq!(to_rust_struct_name("SequentialAgentConfig"), "SequentialAgent");
    }

    #[test]
    fn codegen_default_for_type() {
        assert_eq!(rust_default_for_type("String", false), "String::new()");
        assert_eq!(rust_default_for_type("bool", false), "false");
        assert_eq!(rust_default_for_type("f64", false), "0.0");
        assert_eq!(rust_default_for_type("Vec<String>", false), "Vec::new()");
        assert_eq!(rust_default_for_type("String", true), "None");
        assert_eq!(rust_default_for_type("serde_json::Value", false), "Default::default()");
    }

    #[test]
    fn codegen_generates_struct() {
        let agent = make_agent(
            "BaseAgentConfig",
            AgentKind::Base,
            vec![
                make_field("description", "String", true),
                make_field("subAgents", "Vec<String>", true),
            ],
            vec![],
        );
        let schema = make_schema_with(vec![agent], vec![]);
        let code = generate(&schema);

        assert!(code.contains("pub struct BaseAgentConfig {"), "Should contain config struct");
        assert!(code.contains("pub name: String,"), "Should contain name field");
        assert!(
            code.contains("pub description: Option<String>,"),
            "Should contain optional description field, got:\n{}",
            code
        );
        assert!(
            code.contains("pub sub_agents: Option<Vec<String>>,"),
            "Should contain snake_case field with Option wrapper"
        );
    }

    #[test]
    fn codegen_generates_builder() {
        let agent = make_agent(
            "LlmAgentConfig",
            AgentKind::Llm,
            vec![
                make_field("model", "String", true),
                make_field("tools", "Vec<String>", true),
            ],
            vec![],
        );
        let schema = make_schema_with(vec![agent], vec![]);
        let code = generate(&schema);

        assert!(code.contains("pub struct LlmAgentBuilder {"), "Should contain builder struct");
        assert!(code.contains("pub fn new(name: impl Into<String>) -> Self"), "Should contain builder new");
        assert!(code.contains("pub fn model(mut self, value: String) -> Self"), "Should contain model setter");
        assert!(code.contains("pub fn tools(mut self, value: Vec<String>) -> Self"), "Should contain tools setter");
        assert!(code.contains("pub fn build(self) -> LlmAgent"), "Should contain build method");
    }

    #[test]
    fn codegen_handles_optional_fields() {
        let agent = make_agent(
            "TestAgentConfig",
            AgentKind::Base,
            vec![
                make_field("required_field", "String", false),
                make_field("optionalField", "f64", true),
            ],
            vec![],
        );
        let schema = make_schema_with(vec![agent], vec![]);
        let code = generate(&schema);

        // Required field: no Option wrapper
        assert!(
            code.contains("pub required_field: String,"),
            "Required field should not be wrapped in Option"
        );
        // Optional field: Option wrapper
        assert!(
            code.contains("pub optional_field: Option<f64>,"),
            "Optional field should be wrapped in Option"
        );

        // Builder: optional setter wraps in Some
        assert!(
            code.contains("self.config.optional_field = Some(value);"),
            "Optional setter should wrap in Some"
        );
        // Builder: required setter assigns directly
        assert!(
            code.contains("self.config.required_field = value;"),
            "Required setter should assign directly"
        );
    }

    #[test]
    fn codegen_generates_default_impl() {
        let agent = make_agent(
            "BaseAgentConfig",
            AgentKind::Base,
            vec![
                make_field("description", "String", true),
                make_field("maxRetries", "f64", false),
                make_field("enabled", "bool", false),
                make_field("subAgents", "Vec<String>", false),
            ],
            vec![],
        );
        let schema = make_schema_with(vec![agent], vec![]);
        let code = generate(&schema);

        assert!(code.contains("impl Default for BaseAgentConfig {"), "Should contain Default impl");
        assert!(code.contains("description: None,"), "Optional field default should be None");
        assert!(code.contains("max_retries: 0.0,"), "f64 default should be 0.0");
        assert!(code.contains("enabled: false,"), "bool default should be false");
        assert!(code.contains("sub_agents: Vec::new(),"), "Vec default should be Vec::new()");
    }

    #[test]
    fn codegen_generates_agent_trait_for_composition() {
        let agent = make_agent(
            "SequentialAgentConfig",
            AgentKind::Sequential,
            vec![],
            vec![],
        );
        let schema = make_schema_with(vec![agent], vec![]);
        let code = generate(&schema);

        assert!(
            code.contains("impl Agent for SequentialAgent {"),
            "Should contain Agent trait impl for composition agent"
        );
        assert!(
            code.contains("fn name(&self) -> &str {"),
            "Should contain name method"
        );
        assert!(
            code.contains("todo!(\"SequentialAgent::run_live\")"),
            "Should contain todo! stub"
        );
    }

    #[test]
    fn codegen_skips_agent_trait_for_non_composition() {
        let agent = make_agent(
            "LlmAgentConfig",
            AgentKind::Llm,
            vec![],
            vec![],
        );
        let schema = make_schema_with(vec![agent], vec![]);
        let code = generate(&schema);

        assert!(
            !code.contains("impl Agent for LlmAgent {"),
            "Should NOT contain Agent trait impl for non-composition agent"
        );
        assert!(
            code.contains("// Agent trait impl for LlmAgent should be provided by the runtime crate."),
            "Should contain comment about runtime crate"
        );
    }

    #[test]
    fn codegen_generates_tool_struct() {
        let tool = ToolDef {
            name: "FunctionToolParams".to_string(),
            description: Some("Parameters for a function tool.".to_string()),
            fields: vec![
                make_field("functionName", "String", false),
                make_field("description", "String", true),
                make_field("parameters", "serde_json::Value", true),
            ],
            extends: None,
        };
        let schema = make_schema_with(vec![], vec![tool]);
        let code = generate(&schema);

        assert!(
            code.contains("pub struct FunctionToolParams {"),
            "Should generate tool params struct"
        );
        assert!(
            code.contains("pub function_name: String,"),
            "Should contain snake_case field"
        );
        assert!(
            code.contains("pub parameters: Option<serde_json::Value>,"),
            "Should contain optional field"
        );
    }

    #[test]
    fn codegen_generates_callback_comments() {
        let agent = make_agent(
            "LlmAgentConfig",
            AgentKind::Llm,
            vec![],
            vec![CallbackDef {
                name: "beforeModelCallback".to_string(),
                ts_signature: "BeforeModelCallback".to_string(),
                description: Some("Called before the model runs.".to_string()),
            }],
        );
        let schema = make_schema_with(vec![agent], vec![]);
        let code = generate(&schema);

        assert!(
            code.contains("// Callback: beforeModelCallback"),
            "Should contain callback name comment"
        );
        assert!(
            code.contains("// TS signature: BeforeModelCallback"),
            "Should contain TS signature comment"
        );
        assert!(
            code.contains("// Called before the model runs."),
            "Should contain callback description"
        );
        assert!(
            code.contains("// TODO: Implement Rust callback type"),
            "Should contain TODO comment"
        );
    }

    #[test]
    fn codegen_header_contains_source_info() {
        let schema = make_schema_with(vec![], vec![]);
        let code = generate(&schema);

        assert!(code.contains("AUTO-GENERATED by adk-transpiler"));
        assert!(code.contains("Source: adk-js"));
        assert!(code.contains("Generated: 2026-03-02T00:00:00Z"));
    }

    #[test]
    fn codegen_parallel_and_loop_get_agent_impl() {
        let parallel = make_agent("ParallelAgentConfig", AgentKind::Parallel, vec![], vec![]);
        let loop_agent = make_agent("LoopAgentConfig", AgentKind::Loop, vec![], vec![]);
        let schema = make_schema_with(vec![parallel, loop_agent], vec![]);
        let code = generate(&schema);

        assert!(code.contains("impl Agent for ParallelAgent {"));
        assert!(code.contains("impl Agent for LoopAgent {"));
        assert!(code.contains("todo!(\"ParallelAgent::run_live\")"));
        assert!(code.contains("todo!(\"LoopAgent::run_live\")"));
    }
}
