// AUTO-GENERATED by adk-transpiler -- do not edit manually
// Source: adk-js
// Generated: 2026-03-02T00:48:41Z

#![allow(dead_code, unused_imports, clippy::type_complexity)]

use std::sync::Arc;
use async_trait::async_trait;
use crate::{Agent, AgentError, InvocationContext, ToolFunction};
use crate::context::AgentEvent;

// BaseAgent — base class, fields merged into child agents via inheritance.

// ---- LlmAgent ----

/// The configuration options for creating an LLM-based agent.
/// (Inherits fields from BaseAgent)
// Cannot derive Clone: contains trait objects
pub struct LlmAgentConfig {
    pub name: String,
    /// The model to use for the agent.
    pub model: Option<String>,
    /// Instructions for the LLM model, guiding the agent's behavior.
    pub instruction: Option<String>,
    /// Instructions for all the agents in the entire agent tree. ONLY the globalInstruction in root agent will take effect. For example: use globalInstruction to make all agents have a stable identity or personality.
    pub global_instruction: Option<String>,
    /// Tools available to this agent.
    pub tools: Option<Vec<Arc<dyn ToolFunction>>>,
    /// The additional content generation configurations. NOTE: not all fields are usable, e.g. tools must be configured via `tools`, thinking_config must be configured via `planner` in LlmAgent. For example: use this config to adjust model temperature, configure safety settings, etc.
    pub generate_content_config: Option<serde_json::Value>,
    /// Disallows LLM-controlled transferring to the parent agent. NOTE: Setting this as True also prevents this agent to continue reply to the end-user. This behavior prevents one-way transfer, in which end-user may be stuck with one agent that cannot transfer to other agents in the agent tree.
    pub disallow_transfer_to_parent: Option<bool>,
    /// Disallows LLM-controlled transferring to the peer agents.
    pub disallow_transfer_to_peers: Option<bool>,
    /// Controls content inclusion in model requests. Options:   default: Model receives relevant conversation history   none: Model receives no prior history, operates solely on current   instruction and input
    pub include_contents: Option<String>,
    /// The input schema when agent is used as a tool.
    pub input_schema: Option<serde_json::Value>,
    /// The output schema when agent replies.
    pub output_schema: Option<serde_json::Value>,
    /// The key in session state to store the output of the agent. Typically use cases: - Extracts agent reply for later use, such as in tools, callbacks, etc. - Connects agents to coordinate with each other.
    pub output_key: Option<String>,
    /// Processors to run before the LLM request is sent.
    pub request_processors: Option<Vec<serde_json::Value>>,
    /// Processors to run after the LLM response is received.
    pub response_processors: Option<Vec<serde_json::Value>>,
    /// Instructs the agent to make a plan and execute it step by step.
    pub code_executor: Option<serde_json::Value>,
    pub description: Option<String>,
    pub parent_agent: Option<Arc<dyn Agent>>,
    pub sub_agents: Option<Vec<Arc<dyn Agent>>>,
    /// Callbacks to be called before calling the LLM.
    pub before_model_callback: Option<Box<dyn Fn(&InvocationContext) + Send + Sync>>,
    /// Callbacks to be called after calling the LLM.
    pub after_model_callback: Option<Box<dyn Fn(&InvocationContext) + Send + Sync>>,
    /// Callbacks to be called before calling the tool.
    pub before_tool_callback: Option<Box<dyn Fn(&InvocationContext) + Send + Sync>>,
    /// Callbacks to be called after calling the tool.
    pub after_tool_callback: Option<Box<dyn Fn(&InvocationContext) + Send + Sync>>,
    pub before_agent_callback: Option<Box<dyn Fn(&InvocationContext) + Send + Sync>>,
    pub after_agent_callback: Option<Box<dyn Fn(&InvocationContext) + Send + Sync>>,
}

impl LlmAgentConfig {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            model: None,
            instruction: None,
            global_instruction: None,
            tools: None,
            generate_content_config: None,
            disallow_transfer_to_parent: None,
            disallow_transfer_to_peers: None,
            include_contents: None,
            input_schema: None,
            output_schema: None,
            output_key: None,
            request_processors: None,
            response_processors: None,
            code_executor: None,
            description: None,
            parent_agent: None,
            sub_agents: None,
            before_model_callback: None,
            after_model_callback: None,
            before_tool_callback: None,
            after_tool_callback: None,
            before_agent_callback: None,
            after_agent_callback: None,
        }
    }
}

pub struct LlmAgentBuilder {
    config: LlmAgentConfig,
}

impl LlmAgentBuilder {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            config: LlmAgentConfig::new(name),
        }
    }

    pub fn model(mut self, value: String) -> Self {
        self.config.model = Some(value);
        self
    }

    pub fn instruction(mut self, value: String) -> Self {
        self.config.instruction = Some(value);
        self
    }

    pub fn global_instruction(mut self, value: String) -> Self {
        self.config.global_instruction = Some(value);
        self
    }

    pub fn tools(mut self, value: Vec<Arc<dyn ToolFunction>>) -> Self {
        self.config.tools = Some(value);
        self
    }

    pub fn generate_content_config(mut self, value: serde_json::Value) -> Self {
        self.config.generate_content_config = Some(value);
        self
    }

    pub fn disallow_transfer_to_parent(mut self, value: bool) -> Self {
        self.config.disallow_transfer_to_parent = Some(value);
        self
    }

    pub fn disallow_transfer_to_peers(mut self, value: bool) -> Self {
        self.config.disallow_transfer_to_peers = Some(value);
        self
    }

    pub fn include_contents(mut self, value: String) -> Self {
        self.config.include_contents = Some(value);
        self
    }

    pub fn input_schema(mut self, value: serde_json::Value) -> Self {
        self.config.input_schema = Some(value);
        self
    }

    pub fn output_schema(mut self, value: serde_json::Value) -> Self {
        self.config.output_schema = Some(value);
        self
    }

    pub fn output_key(mut self, value: String) -> Self {
        self.config.output_key = Some(value);
        self
    }

    pub fn request_processors(mut self, value: Vec<serde_json::Value>) -> Self {
        self.config.request_processors = Some(value);
        self
    }

    pub fn response_processors(mut self, value: Vec<serde_json::Value>) -> Self {
        self.config.response_processors = Some(value);
        self
    }

    pub fn code_executor(mut self, value: serde_json::Value) -> Self {
        self.config.code_executor = Some(value);
        self
    }

    pub fn description(mut self, value: String) -> Self {
        self.config.description = Some(value);
        self
    }

    pub fn parent_agent(mut self, value: Arc<dyn Agent>) -> Self {
        self.config.parent_agent = Some(value);
        self
    }

    pub fn sub_agents(mut self, value: Vec<Arc<dyn Agent>>) -> Self {
        self.config.sub_agents = Some(value);
        self
    }

    pub fn build(self) -> LlmAgent {
        LlmAgent { config: self.config }
    }
}

pub struct LlmAgent {
    pub config: LlmAgentConfig,
}

// Agent trait impl for LlmAgent should be provided by the application.


// ---- LoopAgent ----

/// The configuration options for creating a loop agent.
/// (Inherits fields from BaseAgent)
// Cannot derive Clone: contains trait objects
pub struct LoopAgentConfig {
    pub name: String,
    /// The maximum number of iterations the loop agent will run. If not provided, the loop agent will run indefinitely.
    pub max_iterations: Option<f64>,
    pub description: Option<String>,
    pub parent_agent: Option<Arc<dyn Agent>>,
    pub sub_agents: Option<Vec<Arc<dyn Agent>>>,
    pub before_agent_callback: Option<Box<dyn Fn(&InvocationContext) + Send + Sync>>,
    pub after_agent_callback: Option<Box<dyn Fn(&InvocationContext) + Send + Sync>>,
}

impl LoopAgentConfig {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            max_iterations: None,
            description: None,
            parent_agent: None,
            sub_agents: None,
            before_agent_callback: None,
            after_agent_callback: None,
        }
    }
}

pub struct LoopAgentBuilder {
    config: LoopAgentConfig,
}

impl LoopAgentBuilder {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            config: LoopAgentConfig::new(name),
        }
    }

    pub fn max_iterations(mut self, value: f64) -> Self {
        self.config.max_iterations = Some(value);
        self
    }

    pub fn description(mut self, value: String) -> Self {
        self.config.description = Some(value);
        self
    }

    pub fn parent_agent(mut self, value: Arc<dyn Agent>) -> Self {
        self.config.parent_agent = Some(value);
        self
    }

    pub fn sub_agents(mut self, value: Vec<Arc<dyn Agent>>) -> Self {
        self.config.sub_agents = Some(value);
        self
    }

    pub fn build(self) -> LoopAgent {
        LoopAgent { config: self.config }
    }
}

pub struct LoopAgent {
    pub config: LoopAgentConfig,
}

#[async_trait]
impl Agent for LoopAgent {
    fn name(&self) -> &str {
        &self.config.name
    }

    fn sub_agents(&self) -> Vec<Arc<dyn Agent>> {
        self.config.sub_agents.clone().unwrap_or_default()
    }

    async fn run_live(&self, ctx: &mut InvocationContext) -> Result<(), AgentError> {
        let inner = crate::agents::loop_agent::LoopAgent::new(
            &self.config.name,
            self.sub_agents(),
            self.config.max_iterations.map(|v| v as u32).unwrap_or(10),
        );
        inner.run_live(ctx).await
    }
}


// ---- ActiveStreamingToolParams ----

/// The parameters for creating an ActiveStreamingTool.
#[derive(Debug, Clone, Default)]
pub struct ActiveStreamingToolParams {
    pub task: Option<serde_json::Value>,
    pub stream: Option<serde_json::Value>,
}


